### ISSUE TITLE
How to deal with multiple subplots?

### ISSUE THREAD

**Issue by xindi-dumbledore** [Phlya/adjustText#102]
Hi really love this tool. Maybe I'm missing something.... but how to use this on multiple subplots? I tried to use it directly and it just pull all the text in one subplot to another which is not ideal... Could you provide some examples on this? Thanks!

**Comment by Phlya** [comment]
Glad you like it! There are example in the docs, here is a separate page specially dedicated to this after someone else had this problem: https://adjusttext.readthedocs.io/en/latest/Examples-for-multiple-subplots.html

Main point - use the `ax` argument. Hope this helps!
