### ISSUE TITLE
only_move not working

### ISSUE THREAD

**Issue by jolenscki** [Phlya/adjustText#107]
I'm trying to use the library to resolve an overlapping in the annotation of the last value of a series plot. This is a sample of the code I'm writing:

```
import matplotlib
import matplotlib.pyplot as plt
from adjustText import adjust_text
import numpy as np

foo = np.linspace(1, 100,  1000)
bar = np.linspace(1, 100.1, 1000)
x = np.linspace(0,1,1000)

w, h = plt.figaspect(9/16) 
fig = plt.figure(figsize=(w, h), dpi=300, frameon=False)
ax = plt.gca()

plt.xlim(x[0], x[-1])

ax.plot(x, foo, label='Foo', color='b')
plt.annotate(f'{foo[-1]}',
         xy = (1, foo[-1]),
         xytext=(8, 0), 
         xycoords=('axes fraction', 'data'),
         textcoords='offset points',
         color='b'
        )

ax.plot(x, bar, label='Bar', color='orange')
plt.annotate(f'{bar[-1]}',
         xy = (1, bar[-1]),
         xytext=(8, 0), 
         xycoords=('axes fraction', 'data'),
         textcoords='offset points',
         color='orange'
        )
```

This code generates this figure:

![image](https://user-images.githubusercontent.com/11397443/102662220-1ed56e80-415d-11eb-80c5-40f0746fed37.png)

Then, I tried to use ```adjust_text``` to fix the annotation overlap and passed the ```move_only``` dictionary to avoid to have movements of the texts in the ```x-axis``` .

```
annotations = [child for child in ax.get_children() if isinstance(child, matplotlib.text.Annotation)]
adjust_text(annotations,
            only_move={'points':'xy', 'text':'y', 'objects':'xy'},
            autoalign='y',
           )
```

 I expected something like this:

![image](https://user-images.githubusercontent.com/11397443/102662268-4593a500-415d-11eb-916d-2a26729311ed.png)

But got this:

![image](https://user-images.githubusercontent.com/11397443/102662368-78d63400-415d-11eb-97cb-a297f41fbe57.png)

**Comment by Phlya** [comment]
You are using annotations instead of texts... Can you try plt.text instead of plt.annotate?

**Comment by jolenscki** [comment]
I've tried to use plt.text: 

```
import matplotlib
import matplotlib.pyplot as plt
from adjustText import adjust_text
import numpy as np

foo = np.linspace(1, 100,  1000)
bar = np.linspace(1, 100.1, 1000)
x = np.linspace(0,1,1000)

w, h = plt.figaspect(9/16) 
fig = plt.figure(figsize=(w, h), dpi=300, frameon=False)
ax = plt.gca()

plt.xlim(x[0], x[-1])

ax.plot(x, foo, label='Foo', color='b')
plt.text(1, foo[-1], f'{foo[-1]}')

ax.plot(x, bar, label='Bar', color='orange')
plt.text(1, bar[-1], f'{bar[-1]}')


texts = [child for child in ax.get_children() if isinstance(child, matplotlib.text.Text)]

adjust_text(texts,
            only_move={'points':'xy', 'text':'y', 'objects':'xy'},
            autoalign='y',
            set_clip_on=True
           )
```

But it seems is not working either. The figure returned is still overlapping with the plot

**Comment by Phlya** [comment]
I can't reproduce it, i.e. my results are different - are you using the version from master? One thing to keep in mind though, is that the texts will always end up inside the axes, so if you were trying to keep them outside - sorry!

**Comment by jolenscki** [comment]
I'm using the version from master! And was really trying to make the texts be outside of the axes. If it's impossible, so that explains a lot! Thank you for your attention!
