### ISSUE TITLE
Labels all over the place

### ISSUE THREAD

**Issue by am-thyst** [Phlya/adjustText#109]
First of all, thanks for making this package! I'm sure it will come in very handy.

Unfortunately I can't post a completely reproducible example due to the data restrictions, but could you tell me where I'm going wrong?

I used the following:
```python
adjust_text(text_list,only_move={'points':'y', 'texts':'y'},force_points=0.15,lw=0.5)
```

I'm not really sure what all of the kwargs mean. I end up with the following:

![image](https://user-images.githubusercontent.com/41115380/104915315-5ddb2780-5988-11eb-8214-45f08410b5e9.png)

And without adjust_text:
![image](https://user-images.githubusercontent.com/41115380/104915412-8105d700-5988-11eb-9263-27de95b57c37.png)

I just need to separate the cluster of labels a bit. How would I go about adjusting the kwargs to improve this?

**Comment by Phlya** [comment]
It looks like something is not going right. Are you using multiple subplots or something else? adjust_text never puts new labels outside the axes limits, and getting some of them outside is a good indications something is wrong with the bigger picture.

You can make a reproducible example with randomly generated data. Very often the process of making an example leads to finding the problem!
