### ISSUE TITLE
Arrow crossing point

### ISSUE THREAD

**Issue by Khris777** [Phlya/adjustText#11]
Does the routine check if an arrow crosses a point?
I have a case with medium difficulty and I was able to configure it fine setting all values for force and expand to 1.5, however there is one case where an arrow goes right through a point and I can't resolve it without strongly altering the values which worsens the layout of the rest.

**Comment by Phlya** [comment]
No, sorry, it doesn't check that, and I can't imagine how to implement this... If you are making just one figure, it's easiest if you just manually move that one annotation.
