### ISSUE TITLE
Is it possible to arrange the annotation in an ordered way?

### ISSUE THREAD

**Issue by zhijun888** [Phlya/adjustText#115]
Hi, Thanks for the excellent code, which is mainly used to avoid the overlap of the annotations. 
However, the derived arrangement of these annotations might look a bit messy, although they have been clearly separated from each other.
Therefore, can we control the direction of the movement during the optimization to ensure the final output looks ordered, such as in a clockwise or fish-bone placement?

Thanks a lot!
Zhijun

**Comment by Phlya** [comment]
Hi Zhijun,

Sorry, no, that is not possible at the moment.

**Comment by zhijun888** [comment]
> Hi Zhijun,
> 
> Sorry, no, that is not possible at the moment.

Thanks for the clarifying, Phlya. 
But I wonder if I can access the source code of this lib and make some trials?  since the current code already allows the movement in a certain direction like x or y, so it seems possible to apply other constraints on the movement of the texts.

Regards
Zhijun

**Comment by Phlya** [comment]
Certainly, that's why it's on GitHub! I'll be happy to see any PRs that improve the functionality.

**Comment by zhijun888** [comment]
> Certainly, that's why it's on GitHub! I'll be happy to see any PRs that improve the functionality.

OK, but how can i make some modification or edit? Thanks Phlya.

**Comment by Phlya** [comment]
Here is one of the guides I found online about how it works: https://opensource.com/article/19/7/create-pull-request-github
