### ISSUE TITLE
Moves text annotations from outside to inside of graph

### ISSUE THREAD

**Issue by DBinMia** [Phlya/adjustText#119]
Using sample "flights" data set. Add text to far right of the graph to label lineplot end points. Attempt to use adjustText to adjust the text y positions so labels don't over lap. adjust_text() will adjust the text, but move it back inside the graph and overlap the lines.  Code, before and after images below.

flights = sns.load_dataset('flights')
months = flights['month'].unique()

fig_dims = (7, 5)
fig, ax = plt.subplots(figsize=fig_dims)
sns.lineplot(ax=ax, data=flights, x='year', y='passengers', hue='month',
             ci=None, palette=sns.color_palette('tab20b', n_colors=12), linewidth=2)
ax.set_xlim(1950, 1960)
plt.legend(fontsize=8)

texts = []

for iteration, l in enumerate(ax.lines):
    y = l.get_ydata()
    if len(y)>0:
         texts.append(ax.text(1960, y[-1], months[iteration]+f' ({y[-1]:.0f})', ha='left', va='center',
                 fontsize=8, color=l.get_color()))

adjust_text(texts, ax=ax, autoalign=False, only_move={'text':'y'}, ha='left')
plt.show()

<img width="514" alt="before" src="https://user-images.githubusercontent.com/91749770/135656290-26bc75e3-9074-42f5-a9af-9639f39880e8.png">

<img width="485" alt="after" src="https://user-images.githubusercontent.com/91749770/135656313-54e5a6f3-331b-4cea-84d2-0608a78d6825.png">

**Comment by Phlya** [comment]
Two options: extend the X axis to include all texts, or add a second axes object (which you can hide completely) and add the annotations to it.

It shouldn't be difficult to add an option for this, though, I think...

**Comment by DBinMia** [comment]
Thanks. I can change the code slightly to:

ax.set_xlim(1950, 1962)
plt.legend(loc='upper left', fontsize=8)

This behaves better (although Apr and Oct always remain overlapped). Since the data cuts off at 1960, I prefer not having to have the axis go out to 1962. I'll try your suggestion of adding a second axis. I'm looking for an option that will not alter the x position at all and only repels in the y direction until everything fits.

**Comment by DBinMia** [comment]
Thanks for your suggestions. The code below adjusts the graph close to my goal, with the exception that Apr and Oct still overlap after adjust_text() is used.

flights = sns.load_dataset('flights')
months = flights['month'].unique()

fig_dims = (9, 6)
fig, ax = plt.subplots(figsize=fig_dims)
sns.lineplot(ax=ax, data=flights, x='year', y='passengers', hue='month',
             ci=None, palette=sns.color_palette('tab20b', n_colors=12), linewidth=2)
ax.set_xlim(1950, 1962)
ax.axvspan(1960, 1962, facecolor='white')

plt.xlabel('Year', fontsize=12)
plt.ylabel('Passengers', fontsize=12)
plt.legend(loc='upper left', fontsize=8)
plt.xticks(range(1950, 1960, 2))

texts = []

for iteration, l in enumerate(ax.lines):
    y = l.get_ydata()
    if len(y)>0:
         texts.append(ax.text(1960, y[-1], months[iteration]+f' ({y[-1]:.0f})', ha='left', va='center',
                 fontsize=8, color=l.get_color()))

adjust_text(texts, ax=ax, autoalign=False, only_move={'text':'y'}, ha='left')
plt.show()

<img width="367" alt="final" src="https://user-images.githubusercontent.com/91749770/135670805-dc1fbfd5-5943-4f63-92fb-f372da4f3e70.png">

**Comment by Phlya** [comment]
Nice! You can try to use autoalign='y' to help separate Apr and Oct. Do they have exactly the same value there? It's impossible to separate them then without autoalignment.

**Comment by DBinMia** [comment]
Yes, setting autoalign='y' separates the final overlaps.  I'll close this since my goal has been met. Thanks.

**Comment by Phlya** [comment]
Excellent, glad to hear it helped!
