### ISSUE TITLE
Non-Unique Data Points Still Have Overlapping Labels

### ISSUE THREAD

**Issue by Elliptica1** [Phlya/adjustText#12]
If we make a graph with multiple datapoints at the same location (e.g. two points at (2,3) with different labels), the annotations still overlap. 
![overlap](https://cloud.githubusercontent.com/assets/24662122/21334355/9c74696c-c60b-11e6-90f4-423c5d9f7c98.JPG)

**Comment by Phlya** [comment]
Yes, thank you, it has been reported already, I haven't found the time yet to fix it. Would be happy to accept a PR though!

**Comment by Phlya** [comment]
I believe with the latest commit this has been fixed, please let me know whether it helps you.

**Comment by Phlya** [comment]
If there is no more than 9 non-unique data points (number of options of alignment, which is the step when these should be resolved), and if there is a lot of other points/labels around it's not guaranteed to work.
I am closing this issue now.

**Comment by Elliptica1** [comment]
It seems to be working quite well now, thank you!
