### ISSUE TITLE
compatibility with session_info

### ISSUE THREAD

**Issue by brandonlind** [Phlya/adjustText#126]
Hello, I often use [session_info](https://pypi.org/project/session-info/) to keep version info at the top of my jupyter notebooks.

I imported `adjustText` but `session_info.show()` does not pick up version number. Is this something that could be adjusted? I believe `session_info` attempts to retrieve the version from the following attributes (see lines 212-221 [here](https://gitlab.com/joelostblom/session_info/-/blob/master/session_info/main.py)):

- `package.__version__`
- `package.version`
- `package.VERSION`

---
# example
![Screen Shot 2022-04-29 at 11 36 10 AM](https://user-images.githubusercontent.com/8821725/165977300-764bd2f2-09d2-42bd-aa04-e2b94cf6d3c7.png)

---
# workaround
here is my work-around where I just set the version attribute:
![Screen Shot 2022-04-29 at 11 43 25 AM](https://user-images.githubusercontent.com/8821725/165978527-2cae5d87-cd41-4fe9-9332-0c150c24ca2c.png)

**Comment by Phlya** [comment]
Not sure what/when was changed, but it works for me with the latest master.
