### ISSUE TITLE
Inconsistency with Lines

### ISSUE THREAD

**Issue by Elliptica1** [Phlya/adjustText#13]
There seems to be some inconsistency with when lines appear. E.g. a line appears for 9 but not 10 (I think because 9 is close to the point) but 15 and 11, which both refer to the same point, have no lines even though the 11 is moved far away. This makes it a bit ambiguous about which point 11 actually refers to.

Orig:

![orig](https://cloud.githubusercontent.com/assets/24662122/21335232/339ca362-c612-11e6-8595-2395518a96e2.JPG)

After:

![inconsistency](https://cloud.githubusercontent.com/assets/24662122/21335235/3c13e762-c612-11e6-9357-70cbcef8af07.JPG)

**Comment by Phlya** [comment]
Yes, I have noticed this, but I think this is a matplotlib problem, since in my code I ask it to do exactly the same thing for all annotations, and often when the annotation is close to the point, it doesn't show the line... I can't do anything about this on my side.

**Comment by Phlya** [comment]
I thought I figured out the problem (https://github.com/Phlya/adjustText/issues/32) although wasn't sure how to solve it, but actually some testing shows this is not the case - but also in same simple random examples I don't see this problem any more. Could you check whether this is still a problem, and if it is, share a reproducible example?

**Comment by Phlya** [comment]
I am still not sure what was the cause, but I think it's solved in the latest version here.
