### ISSUE TITLE
Please include LICENSE file in distribution tarball

### ISSUE THREAD

**Issue by penguinpee** [Phlya/adjustText#131]
Hi. I'm currently packaging adjustText for Fedora as a dependency for [plotnine](https://pypi.org/project/plotnine/). I noticed that the LICENSE files is missing from the tarball uploaded to [PyPI](https://pypi.org/project/adjustText/#files) (latest release).

The MIT license requires you to distribute the license text:

> The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

Would you be so kind as to include the LICENSE file in the next release? It makes it a little easier for me getting the package approved in Fedora. In case you are interested, the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text) have more info.

**Comment by oscargus** [comment]
From 0.8 this seems to happen. Can you please confirm?

**Comment by penguinpee** [comment]
Sorry for the late reply. Our upstream release monitoring didn't pick up the `0.8` release, because it was set to _semantic_ versioning and that sorts the pre-releases higher than the stable release. :face_in_clouds: 

I can confirm the `LICENSE` file is now included in the `sdist` tarball. Thank you!

Any plans on adding a description for PyPI? :wink:
