### ISSUE TITLE
Type-hinting of force_points is wrong

### ISSUE THREAD

**Issue by JasonMendoza2008** [Phlya/adjustText#132]
The type-hinting of the argument `force_points` from the function `adjust_text()` is wrong.

Instead of
`force_points: float = (0.2, 0.5)`

It should be:
`force_points: float | tuple[float, float] = (0.2, 0.5)`
Or the equivalent type-hinting for Python < 3.10.

**Comment by JasonMendoza2008** [comment]
The same applies to the argument `force_text` from the function `adjust_text()`: its type-hinting is wrong.

**Comment by Phlya** [comment]
Thank you, feel free to submit a PR to fix this!

**Comment by JasonMendoza2008** [comment]
Should I fork the repo and make a PR or can I directly create a branch here?

**Comment by Phlya** [comment]
I think you have to fork it.
