### ISSUE TITLE
Adjustment of texts when y limits exist

### ISSUE THREAD

**Issue by seareale** [Phlya/adjustText#135]
Thank you for providing a good package.

I randomly generated data with values for one axis and drew a graph using `scatter` with y limits.
```python
import numpy as np
import matplotlib.pyplot as plt
from adjustText import adjust_text


point_list = sorted([np.random.random(1)*150 + 100 for _ in range(20)])
point_count = len(point_list)

fig, ax = plt.subplots(figsize=(5,2))
ax.set_ylim(-1, 1)
ax.set_xlim(0, 600)
ax.scatter(point_list, [0 for _ in point_list], edgecolors='black')

texts=[]
for idx, x in enumerate(point_list):
    texts+=[ax.text(x, 1 if idx %2==0 else -1, idx, fontsize=8)]
adjust_text(texts, va='center', ha='center')
```
and result is below.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/33483699/205272220-40f28e2e-4f11-43bf-a05c-695cc13ce6f1.png">

I want texts to be fixed in specific y value like texts located lower side and spread from side to side. 
Texts located upper side has been adjusted but not fixed y value and not enough margin with each texts.

![image](https://user-images.githubusercontent.com/33483699/205273008-cf73fc0b-e680-4c2d-99ab-8e648e89e761.png)

I want to make it like the figure above. Is there any possible way?

**Comment by Phlya** [comment]
Try adding `autoalign='x', only_move={'points':'x', 'text':'x', 'objects':'x'}` arguments, see how it goes

**Comment by seareale** [comment]
@Phlya Thanks for the reply.
The result is shown below.
![image](https://user-images.githubusercontent.com/33483699/205275877-8fe59376-5f6d-46f0-ab8d-97fb9353bd97.png)

**Comment by Phlya** [comment]
Yeah... try changing force maybe, or the expand arguments.
