### ISSUE TITLE
0.8 breaks positioning at negative locations (on Windows?)

### ISSUE THREAD

**Issue by oscargus** [Phlya/adjustText#140]
```
import matplotlib.pyplot as plt
import adjustText

fig, ax = plt.subplots()

ax.plot([-1, 1], [1, -1])
t = [ax.text(0.5, 0.8, adjustText.__version__), ax.text(-0.5, -0.8, "bar")]
adjustText.adjust_text(t)
fig.savefig('adjust.png')
```
will move the bar-text to 0, 0. Using 0.7 it does work without any issues.

The strange thing is that I only see this on Windows as my tests pass on GitHub Actions. Not sure how comes and if I possibly have some other packages installed that causes this? (Again, just downgrading to 0.7 works on my Windows machine.)

![adjust](https://user-images.githubusercontent.com/8114497/221429267-12fe8427-3e68-4cdf-91e8-e9312b2ac768.png)

![adjust](https://user-images.githubusercontent.com/8114497/221429348-73aa0984-76ce-4c0f-aacc-5815a0900518.png)

**Comment by Phlya** [comment]
Can you try the version from here? https://github.com/Phlya/adjustText/pull/139

Otherwise I have no clue actually, don't have any Windows machines... Sorry.

**Comment by Phlya** [comment]
(Note that available arguments are a little bit different, but overall the algorithm is very similar, and way faster)

**Comment by oscargus** [comment]
I'll try it out later, thanks!

Can just update that the same thing happens on my CentOS 7 office machine... Quite confusing indeed. Will try to debug it a bit more careful as well. I mean, there should be a specific call in `adjustText`(?) that all of a sudden sets it to zero. The only thing I can think of is the unit handling in Matplotlib (as in that is the only thing from the changelog that seems remotely related).

**Comment by Phlya** [comment]
Yeah but you don't really have any units here, it's just a regular plot... Really strange. It could be some platform-dependent bug in mpl, if it's related to that.

Are you using the same backends on all machines?

**Comment by oscargus** [comment]
Turned out that passing `save_steps` affected the results, so I started to look into why. It seems like `plt.draw` wasn't enough in my case for some reason (I use `adjustText` in a library), so I swapped the order and applied the `draw` on the canvas instead. (Seems to work for me even when not supplying an Axes, but easy to do.)
