### ISSUE TITLE
adjust_text removes *center* horizontal alignment

### ISSUE THREAD

**Issue by dekuenstle** [Phlya/adjustText#148]
Whenever I use `adjust_text` on texts, which should have *center* alignment, the result is actually *left*/*right* or *top*/*bottom* aligned–––even if there would be enough space for *center* alignment.
I tried to solve it with the `avoid_self` and `only_move` options, but nothing worked. 

How can I use *center*  alignment with `adjust_text` (optimally just in the *y* direction). 

## Minimal example
```python
plt.scatter([0, 0.5, 1], [0, 0.5, 1])
texts = []
texts.append(plt.text(0.0, 0.1, 'AAA', ha='center', va='center'))
texts.append(plt.text(0.5, 0.6, 'BBB', ha='center', va='center'))
texts.append(plt.text(1.0, 0.9, 'CCC', ha='center', va='center'))
adjust_text(texts)
```
### Actual result (with adjust_text)
![image](https://user-images.githubusercontent.com/734721/234705042-a8696ca4-316d-4a72-bdbb-885649de9ca4.png)

### Expected result (here without adjust_text):
![image](https://user-images.githubusercontent.com/734721/234705114-dd7c2f67-4fb7-4b1e-bc20-87d615bf0ad7.png)

**Comment by Phlya** [comment]
Sorry, it's been a long time... I suspect it was an old version that was causing this, there you could specify autoalign=False to switch this off. With the latest version on github it shouldn't happen I believe.
