### ISSUE TITLE
adjusttext moves all text to a 1x1 box

### ISSUE THREAD

**Issue by evancampbell** [Phlya/adjustText#152]
![compass](https://github.com/Phlya/adjustText/assets/251254/fc5a04d3-b30f-48c1-9995-f24bb3d83d20)

Each of the dots has a label, which are correctly positioned when I don't call adjust_text. When I call it, you can see what happens. All labels are moved to an area with 0,0 as its lower left point and 1,1 as its upper right point. Why would this happen?

**Comment by Phlya** [comment]
Please share the code? You probably call something that changes the axes limits after adjust_text.

**Comment by alk0** [comment]
Same problem.

Versions:

Python 3.11.6
adjustText==0.8
matplotlib==3.8.2

Code:

```python
import matplotlib.pyplot as plt
from adjustText import adjust_text


def test_adjust():
    xx = [-100, -50, 100, 50]
    yy = [0, 50, 0, -50]
    fig, ax = plt.subplots()
    ax.scatter(xx, yy, marker="o")
    texts = []
    for i, (x, y) in enumerate(zip(xx, yy)):
        texts.append(plt.text(x, y, str(i)))
    adjust_text(texts, lim=10)
    plt.show()


test_adjust()
```

Output:

![Figure_1](https://github.com/Phlya/adjustText/assets/10332037/a59273b2-0130-4d14-b33e-36ccf9ca6860)

What am I doing wrong?

**Comment by Phlya** [comment]
I can't reproduce it with the latest version of adjustText. Try upgrading, perhaps?

**Comment by alk0** [comment]
Everything's OK with latest master (both before and after that last-minute update - 1.0b and 1.0)

**Comment by Phlya** [comment]
Great, thank you for checking!

**Comment by alk0** [comment]
Uninstalled, re-installed from PyPI - same result (checked just in case). Thanks!
