### ISSUE TITLE
Add documentation link to the dedicated place

### ISSUE THREAD

**Issue by GegznaV** [Phlya/adjustText#154]
To make it more convenient to find the documentation, please, add the link https://adjusttext.readthedocs.io/ to the repo's description. @Phlya, as a developer, you can do that by clicking the gear icon at position 1 in the screenshot (not visible to me) and pasting the link into the field for the URL.

![image](https://github.com/Phlya/adjustText/assets/12725868/02de5d80-d0a6-46f6-ac5c-59401910645e)

**Comment by Phlya** [comment]
Done, thanks for the suggestion!
