### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by JAGulin** [Phlya/adjustText#156]
On latest release, there was a warning:
"deploy
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
"
https://github.com/Phlya/adjustText/actions/runs/4203049422
v3 has 16. v4 went for 20.
https://github.com/marketplace/actions/checkout?version=v3.6.0
https://github.com/actions/setup-python/commit/93cb78f17ba30b733a6c17d0f21183bdc0140887

Updating to v3 should be enough, but possibly consider if the latest workflow example has other improvements.
https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml

**Comment by Phlya** [comment]
Thank you, I kept getting notifications about this but couldn't be bothered to figure it out. I updated the action to the new one that you linked, I hope it works...

**Comment by JAGulin** [comment]
Maybe I should have said that I have no experience with this, so I hoped you would know. :)

Note that your old script used secrets.PYPI_PASSWORD and new has secrets.PYPI_API_TOKEN, which I'm not sure you have configured.

https://github.com/Phlya/adjustText/commit/5912cc8d426bd7cf029ccdb2b8ff6d55872a2a36

Looking again I read "These are obsolete now and you should remove them from your GitHub repository and revoke them in your PyPI". Not sure why the github instructions didn't say so.
These other instructions looks smart, if you're going to re-do config anyway.

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

https://docs.pypi.org/trusted-publishers/
https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by JAGulin** [comment]
Anyway, I was going to suggest that you consider another release ahead of 1.0. That's an idea if you want to test the release script...

Make 0.8.1 or 0.9 release, with backported stuff?
* documentation on pypi. https://github.com/Phlya/adjustText/commit/ba6c70e9ac409ed52e19d2abaac152b85789abbb
* maybe some more of the new commits are bugfixes to old engine too?
* RTD should default to "stable" 0.8 rather than the "latest" (but have both to select).
** Since you have tags already, this may be a matter of config in the RTD rather than any change in code?
** https://docs.readthedocs.io/en/stable/versions.html

Perhaps prepare fwd compatible if easy:
* fwd compatible only_move: string-only input.
* fwd compatible only_move: "y+" support

PS. I noticed the badge "Documentation Status" says "docs failing". 
https://adjusttext.readthedocs.io/en/latest/
Docs currently say "Revision b54b8553" which was the revision before this update.
Not sure why that would be related to the change, but worth to note.

**Comment by Phlya** [comment]
My god, why do they have to change how things are done all the time... Thank you for the feedback and suggestions. Would you perhaps like to work on this and contribute to the package? I have a very limited bandwidth these days and not much time/energy to invest into this, so would be amazing to get someone else to join in supporting and maintaining the package,

**Comment by JAGulin** [comment]
I understand, and I'd be happy to help, although my engagement was mostly random chance and not the life-long commitment you have. :) Looks like there have been other contributers as well, so maybe possible to get a team together.

Forgive my long messages. I wanted to asses the spirit of the project before making any larger PR. I'll get back with some kind of suggestion for an "old version" branch to see what you think. I can try publishing to a dummy package too, but for the actual release and config it probably ends up in your lap anyway.

If you could have a look at this part while waiting, that would be nice. No hurry otherwise:
* RTD should default to "stable" 0.8 rather than the "latest" (but have both to select).
** Since you have tags already, this may be a matter of config in the RTD rather than any change in code?
** https://docs.readthedocs.io/en/stable/versions.html

**Comment by Phlya** [comment]
I fixed the latest docs so the build passes.

But the stable build is broken, and from what I understand, to fix it I need to make a new release with .readthedocs.yml file included in it... Not too hard, maybe I'll find some time to do it this week.

**Comment by Phlya** [comment]
The stable docs are not as pretty, but looks like they are fixed!
