### ISSUE TITLE
Time Limit

### ISSUE THREAD

**Issue by ekwan** [Phlya/adjustText#158]
Does the time limit still work?

'adjust_text(texts, umap1s, umap2s, time_lim=1, arrowprops=dict(arrowstyle="-", color='k', lw=0.5))'

'AttributeError: 'Annotation' object has no property 'time_lim''

Thanks!

**Comment by Phlya** [comment]
What version are you using? time_lim is an argument in the latest unreleased version that you can get from GitHub, but not in the stable version on PyPI.

**Comment by ekwan** [comment]
I have 0.8, which is the version on PyPI.  Thanks for letting me know!
