### ISSUE TITLE
Feature request: Fix output (specify iteration limit instead of time)

### ISSUE THREAD

**Issue by 136s** [Phlya/adjustText#164]
Hi, thanks for the great package! I have a feature request regarding 1.0b which is under development.

In the current (https://github.com/Phlya/adjustText/commit/e474370b73b95c264da0f79124e95fdc4a5b2dd2) `adjust_text()` function, the `time_lim` argument provides an upper limit to the adjustment. Therefore, the number of iterations in a given time varies from run to run.
However, I would like to expect the output to be constant each time it is executed. So, could you please change it so that the number of iterations can be specified with the `lim` argument, as in the old commit (https://github.com/Phlya/adjustText/commit/b98938fcb06e9c27772c50074f601a45626e8d2a#diff-dad13f6d470744c7e96a6688dcd2337e1608e2fb600d6449360784b86a742e59L450)?

**Comment by 136s** [comment]
I wanted deterministic output, so I added the `iter_lim` argument to `adjust_text()` function in #165.
I verified with the following code that the output does not change each time.

```.py
from pathlib import Path
from adjustText import adjust_text
import matplotlib as mpl
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np


def draw_fig(n_points: int = 80) -> Figure:
    # like the example from https://adjusttext.readthedocs.io/en/latest/Examples.html
    np.random.seed(0)
    x, y = np.random.random((2, n_points))
    fig, ax = plt.subplots()
    ax.plot(x, y, "bo")
    texts = [ax.text(x[i], y[i], f"Text{i}") for i in range(n_points)]
    adjust_text(texts, ax=ax, iter_lim=50)
    plt.close()
    return fig


mpl.rcParams["svg.hashsalt"] = "0"  # make SVG deterministic
svg_files: list[Path] = []
for i in range(2):
    fig = draw_fig()
    filepath = Path(f"fig_{i}.svg")
    svg_files.append(filepath)
    fig.savefig(filepath, metadata={"Creator": None, "Date": None})

assert svg_files[0].read_text() == svg_files[1].read_text(), "SVG files differ"
```

|fig_0.svg|fig_1.svg|
|:---:|:---:|
|![fig_0](https://github.com/Phlya/adjustText/assets/47920723/2d667ffd-f149-4d33-9b9a-05ba395e4938)|![fig_1](https://github.com/Phlya/adjustText/assets/47920723/d4890b84-378e-4c83-ba91-898eef546610)|

<details>
<summary>versions of packages in my environment</summary>

```sh
# Name                    Version                   Build  Channel
bioframe                  0.6.0                    pypi_0    pypi
matplotlib                3.8.2           py312h2e8e312_0    conda-forge
numpy                     1.26.3          py312h8753938_0    conda-forge
python                    3.12.1          h2628c8c_1_cpython    conda-forge
scipy                     1.11.4          py312h8753938_0    conda-forge
```

</details>

If you like this modification, please merge it!

**Comment by Phlya** [comment]
Thank you, I merged your PR!
