### ISSUE TITLE
Version 1.0.3 has a non declared dependency on pandas

### ISSUE THREAD

**Issue by penguinpee** [Phlya/adjustText#168]
I'm not sure how you went about releasing 1.0.3. I just build the updated package just to discover:

```python
  File "/builddir/build/BUILDROOT/python-adjustText-1.0.3-1.fc40.x86_64/usr/lib/python3.12/site-packages/adjustText/__init__.py", line 17, in <module>
    from .arrops import overlap_intervals
  File "/builddir/build/BUILDROOT/python-adjustText-1.0.3-1.fc40.x86_64/usr/lib/python3.12/site-packages/adjustText/arrops.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

That's the newly introduced `arrops.py` making bioframe obsolete. However, it took me a while to discover that the "offending" import statement is only present in the releases (tags v1.0.1, v1.0.2 and v1.0.3) not on master. It was introduced by c4d147cd and appears to be [required](https://github.com/Phlya/adjustText/blob/7be7908bfbc5d0ff1761edf0ba1807741dd96f9e/adjustText/arrops.py#L82) in the version of the file present in the releases, but it has not been added to `requirements.txt`.

However, on master you subsequently removed that dependency again in 1ee0b917. But that commit didn't make it into the releases.

I'll guess in this case the saying will be: _the ~~third~~ fourth time is the charm_. ;)

**Comment by Phlya** [comment]
Made a new release, hopefully no issues now :) Thanks for flagging it!
