### ISSUE TITLE
Labels misplaced in subplots

### ISSUE THREAD

**Issue by wwwald** [Phlya/adjustText#171]
I just found this library, so I may be using it wrongly.
But working with the latest master, I get strange results using `adjust_text` in subplots.

Short code example:
```py
import pandas as pd
from matplotlib import pyplot as plt
from adjusttext import adjust_text

fig, axes = plt.subplots(2, 2, figsize=(10, 7))
from itertools import product

df = pd.DataFrame({"a": [0.5, 1.0, 1.8, 1.6, 0.3], "b": [2.12, 2.56, 2.33, 2.32, 2.46]}, index=["one", "two", "three", "four", "five"])

for title, ax in zip(["plot1", "plot2", "plot3", "plot4"], axes.reshape(-1)):
    df.plot(kind="scatter", x="a", y="b", title=title, ax=ax)
    annotations = [plt.text(row.a, row.b, idx) for idx, row in df.iterrows()]
    adjust_text(annotations, ax=ax, arrowprops={"arrowstyle": "-", "color": "red"})
```
The result:

![image](https://github.com/Phlya/adjustText/assets/39531/9b310bab-49da-4a84-af9a-e18a99d99b44)

What's going wrong here?

**Comment by Phlya** [comment]
Replace
annotations = [**plt**.text(row.a, row.b, idx) for idx, row in df.iterrows()]
with
annotations = [**ax**.text(row.a, row.b, idx) for idx, row in df.iterrows()]

Then it works
