### ISSUE TITLE
Issue with "matplotlib.axes.Axes.annotate" using the arguments "xytext" and "textcoords"

### ISSUE THREAD

**Issue by lendres** [Phlya/adjustText#172]
### Description
It seems that the text coordinate system of "offset points" of the function _matplotlib.axes.Axes.annotate_  confuses _adjust_text_.

From some initial testing, it seems like _adjust_text_ reads the position of the text as the offset position when  _xytext_ and _textcoords_ are provided.

### Function
```python
import numpy                           as np
import matplotlib.pyplot               as plt
from   adjustText                      import adjust_text

def Plot(adjustText=False, **kwargs):
    np.random.seed(0)
    x, y    = np.random.random((2,30))
    fig, ax = plt.subplots()
    plt.plot(x, y, 'bo')
    texts = []
    for i in range(len(x)):
        texts.append(ax.annotate('Text%s' %i, [x[i], y[i]], horizontalalignment="center", verticalalignment="bottom", **kwargs))
    if adjustText:
        adjust_text(texts)
```

### Without XYText
The result is as expected.
```python
Plot(adjustText=False)
Plot(adjustText=True)
```
![image](https://github.com/Phlya/adjustText/assets/8999134/459f7fa3-38ba-4bc4-8bb8-29c3e2e870e9)
![image](https://github.com/Phlya/adjustText/assets/8999134/bfb30dfe-1f2d-4972-bc61-730465eb9233)

### With XYText
The result is not as expected.  It seems _adjust_text_ and the arguments of  _xytext_ and _textcoords_ do not work together.
```python
Plot(adjustText=False, xytext=(0, 5), textcoords="offset points")
Plot(adjustText=True, xytext=(0, 5), textcoords="offset points")
```
![image](https://github.com/Phlya/adjustText/assets/8999134/bccbf430-c6e2-4c06-9b3f-9aa100523e66)
![image](https://github.com/Phlya/adjustText/assets/8999134/203c4cc9-9341-448e-bb25-aad66a4722b4)

**Comment by Phlya** [comment]
adjust_text is not compatible with ax.annotate, it requires specifically as.text.

I could not find a way to extract text bounding box from an annotation object. I think it actually would take the bounding box of the whole annotation, including the text and the "target" positions.

If you know how to do it correctly, let me know or feel free to create a PR.

**Comment by lendres** [comment]
I see your point.  

Respectfully, I might suggest that this is not necessary.  Does one want to be moving the location of the target?  I would not think so.  And I would suggest that _adjust_text_ should not move the entire annotation but just the _text_.

I have found that _adjust_text_ works perfectly on annotations (at least ones without the arrows) so long as the _xytext_ argument is not used.  Using that argument seems to switch the coordinate system of the annotation and cause unexpected results.

**Comment by Phlya** [comment]
But then what's the advantage over using text?

**Comment by lendres** [comment]
Ah, yes.  I prefer it because I like the text moved slightly away from the point for aesthetic reasons.  With annotation, you can specify an offset (_xytext_) of the position in points/pixels/font size (_textcoords_).  The use of text coordinates creates a more consistent offset across multiple plots.  Using the data coordinates, the offset would have to change based on the scale of the specific data.  Annotations make this easy.  I'm sure you can do it with text as well, but it's more difficult.

I have found that by setting _{"xytext" : None, "textcoords" : None}_ you can use _adjust_text_ perfectly fine.  This is my current workflow.  And it certainly could be argued that they should not used together as they are both arranging the position of the text in relation to the point they are labeling.

**Comment by Phlya** [comment]
Could you share a small code example showing this?
