### ISSUE TITLE
Poor Result when avoiding a polygonal curve

### ISSUE THREAD

**Issue by ThomasParistech** [Phlya/adjustText#173]
I'm drawing text labels next to specific points along a curve.

I'd like to avoid collisions between text-boxes but also with the curve itself. Unfortunately passing the curve points in x and y results in a clearly non-optimal solution. As we can see in the screenshot below, ans its zoom, swapping the two resulting text boxes would have been more optimized.

**Question: Am I using `adjust_text` in a incorrect way? Or should I implement a custom solution?** 

```
adjust_text(texts,
            x=curve_x[::10],
            y=curve_y[::10],
            time_lim=10,
            arrowprops=dict(arrowstyle='->', color='red'))
```
N.B.: I've tried to subsample the curve before calling `adjust_text`

![image](https://github.com/Phlya/adjustText/assets/35526351/41031a94-0192-4beb-8d2a-10d5aa57ae64)
![image](https://github.com/Phlya/adjustText/assets/35526351/092435d5-84c5-4b0f-a838-8055dd9dbe5f)

**Comment by Phlya** [comment]
Would you be able to share some example data?

**Comment by Phlya** [comment]
Also - are you using the latest version?

**Comment by ThomasParistech** [comment]
I'm using `adjustText==1.1.1`

Here's a minimal reproducible example (with JSON data)

```
import json
import matplotlib.pyplot as plt
from adjustText import adjust_text

path = "data/test.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)
    curve_x = data["curve_x"]
    curve_y = data["curve_y"]
    list_x = data["list_x"]
    list_y = data["list_y"]
    list_text = data["list_text"]

plt.plot(curve_x, curve_y, color="r", lw=2)
plt.plot(list_x, list_y, '^', color="g", markersize=10)


texts = [plt.text(x, y, txt, ha='center', va='center', fontsize=8)
         for x, y, txt in zip(list_x, list_y, list_text)]


adjust_text(texts,
            x=curve_x,
            y=curve_y,
            time_lim=2,
            arrowprops=dict(arrowstyle='->', color='red'))


plt.axis('equal')
plt.gca().invert_yaxis()

plt.show()
```
![image](https://github.com/Phlya/adjustText/assets/35526351/7d09c975-3174-4b62-97fa-05ee1f974665)

[test.json](https://github.com/Phlya/adjustText/files/15143011/test.json)

**Comment by ThomasParistech** [comment]
I got roughly the same result when removing `plt.axis('equal')` and `plt.gca().invert_yaxis()`
![image](https://github.com/Phlya/adjustText/assets/35526351/4f75dce9-50bf-456a-9dc1-47e327e4899b)

**Comment by Phlya** [comment]
When there are so many points it's a bit tricky. Here is some arguments in the right direction, you can experiment a bit more.
```
adjust_text(texts, x=curve_x, y=curve_y, force_explode=0, force_static=(2e-3, 5e-3),
            time_lim=2, expand=(1, 1),
            arrowprops=dict(arrowstyle="->", color='r', lw=0.5))
```
![image](https://github.com/Phlya/adjustText/assets/2895034/438a1101-aad7-4d75-a4b6-a4c7b83eaca1)

**Comment by ThomasParistech** [comment]
Thanks for the parameter suggestion!
But it turns out that `textalloc` works better in this specific scenario (https://github.com/ckjellson/textalloc/issues/18), I'll use it instead
cheers :)
