### ISSUE TITLE
adjustText 1.1 doesn't work properly anymore

### ISSUE THREAD

**Issue by elcinelif** [Phlya/adjustText#174]
Hi Ilya,

I switched to a new computer therefore imported the latest version of adjustText, however it doesn't do the trick it used to do anymore but it doesn't give any errors either. I am using the exact same script I used to use in my previous computer. I am plotting my data on JupyterLab. Here's the piece of code I'm using. 

```
x = df['Branch length'].to_numpy()
y = df['Mean expansion'].to_numpy()
z = df['Strains'].to_numpy()
std = df['sd'].to_numpy()
categories = df['class'].unique()

plt.figure(figsize=(20, 15))

plt.xlabel('Branch length', fontsize=40)
plt.ylabel('Relative expansion', fontsize=40)
plt.xticks(fontsize=25)
plt.yticks(fontsize=25)
plt.ylim(0, 1.05)
plt.xlim(0, 3.0)

plt.axhline(y=1, color='k', linestyle='-', label='WT E.coli')  
plt.axhline(y=0.117, color='k', linestyle='--', label='ΔcheY')

for category in categories:
    subset = df[df['class'] == category]
    if not subset.empty:
        subset_color = subset['color'].iloc[0]  # Assuming the color is uniform within each category
        subset_x = subset['Branch length'].to_numpy()
        subset_y = subset['Mean expansion'].to_numpy()
        subset_std = subset['sd'].to_numpy()
        plt.scatter(subset_x, subset_y, color=subset_color, s=300, label=category)
        plt.errorbar(subset_x, subset_y, yerr=subset_std, fmt='o', color=subset_color, alpha=0.75, capsize=5)

texts = [plt.text(x[i], y[i], z[i], ha='center', va='center', fontsize=20) for i in range(len(x))]
adjust_text(texts)  



plt.legend(fontsize=20)


#plt.savefig('chromosomal-spreading.svg', format='svg', dpi=1200)
plt.savefig('chromosomal-spreading.png', format='png', dpi=1200)
plt.savefig('chromosomal-spreading-test.svg', format='svg', dpi=1200)`
```
Thank you very much, your help will be greatly appreciated!

**Comment by elcinelif** [comment]
Thanks for your quick response! Here are the results and my data sheet:

![chromosomal-spreading](https://github.com/Phlya/adjustText/assets/51376255/945a272d-5dbd-4165-a35d-f3149aa3641b) => result that I obtained on my old computer with the previous version of adjust text


![chromosomal-spreading](https://github.com/Phlya/adjustText/assets/51376255/2d2dbd5b-c9cd-426b-ad13-b6467a80def2) =>result I obtain 
now with the version 1.1 on my new computer with the exact same script

[chromosome-spreading - Copy.xlsx](https://github.com/Phlya/adjustText/files/15150462/chromosome-spreading.-.Copy.xlsx)

**Comment by Phlya** [comment]
OK... It looks a bit different, but I don't see any issues, texts don't overlap... What is it in particular that you don't like?

**Comment by Phlya** [comment]
`texts = [plt.text(x[i], y[i], z[i], ha='left', va='bottom', fontsize=20) for i in range(len(x))]`

Changing alignment of texts makes the result almost identical to the old one, if that's what you want...

**Comment by elcinelif** [comment]
Text indeed doesn't overlap but labels do overlap with the data points which wasn't the case previously... Your recommendation works nicely, thanks a lot! 

Do you by any chance know why the exact same code creates different outputs with different versions of adjustText?

**Comment by Phlya** [comment]
Great to hear!

Well, the whole algorithm of moving the texts around is more complicated than one might think with a lot of small things that can make a visible impact. I believe now the code tries to respect the text alignment, and if possible doesn't move it at all. While before it actually changed the alignment, and by chance it worked better for your use case. Overall there is no promise that different versions have the same output (hopefully on average the results are better with less fiddling with parameters in newer versions).
