### ISSUE TITLE
Problem using the function 

### ISSUE THREAD

**Issue by rodrigosantis1** [Phlya/adjustText#19]
**Not working in my project, gives the following error:**

/usr/lib64/python2.7/site-packages/matplotlib/artist.pyc in update(self, props)
    737             func = getattr(self, 'set_' + k, None)
    738             if func is None or not callable(func):
--> 739                 raise AttributeError('Unknown property %s' % k)
    740             func(v)
    741             changed = True

AttributeError: Unknown property prefer_move

**Tried to apply in the example, returned the following error:**

In[5]
texts = plot_eucs_covers()
adjust_text(texts, arrowprops=dict(arrowstyle="->", color='r', lw=0.5))

Out[5]
ValueError                                Traceback (most recent call last)
/usr/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    305                 pass
    306             else:
--> 307                 return printer(obj)
    308             # Finally look for special method names
    309             method = get_real_method(obj, self.print_method)

/usr/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
    225 
    226     if 'png' in formats:
--> 227         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    228     if 'retina' in formats or 'png2x' in formats:
    229         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/usr/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in print_figure(fig, fmt, bbox_inches, **kwargs)
    117 
    118     bytes_io = BytesIO()
--> 119     fig.canvas.print_figure(bytes_io, **kw)
    120     data = bytes_io.getvalue()
    121     if fmt == 'svg':

/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.pyc in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2218                 orientation=orientation,
   2219                 bbox_inches_restore=_bbox_inches_restore,
-> 2220                 **kwargs)
   2221         finally:
   2222             if bbox_inches and restore_bbox:

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in print_png(self, filename_or_obj, *args, **kwargs)
    503 
    504     def print_png(self, filename_or_obj, *args, **kwargs):
--> 505         FigureCanvasAgg.draw(self)
    506         renderer = self.get_renderer()
    507         original_dpi = renderer.dpi

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in draw(self)
    444         if __debug__: verbose.report('FigureCanvasAgg.draw', 'debug-annoying')
    445 
--> 446         self.renderer = self.get_renderer(cleared=True)
    447         # acquire a lock on the shared font cache
    448         RendererAgg.lock.acquire()

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in get_renderer(self, cleared)
    463 
    464         if need_new_renderer:
--> 465             self.renderer = RendererAgg(w, h, self.figure.dpi)
    466             self._lastKey = key
    467         elif cleared:

/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in __init__(self, width, height, dpi)
     82         self.height = height
     83         if __debug__: verbose.report('RendererAgg.__init__ width=%s, height=%s'%(width, height), 'debug-annoying')
---> 84         self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
     85         self._filter_renderers = []
     86 

ValueError: width and height must each be below 32768

I am using python 2.7 in a linux machine, any idea of how to solve that?

**Comment by Phlya** [comment]
Mh, can you try using a different matplotlib backend?..

**Comment by rodrigosantis1** [comment]
I tried several backends and still giving the same error message... :(

List I used:
#['pdf', 'pgf', 'Qt4Agg', 'GTK', 'GTKAgg', 'ps', 'agg', 'cairo', 'MacOSX', 'GTKCairo', 'WXAgg', 
#'template', 'TkAgg', 'GTK3Cairo', 'GTK3Agg', 'svg', 'WebAgg', 'CocoaAgg', 'emf', 'gdk', 'WX']

**Comment by Phlya** [comment]
Well, not a single error in your traceback comes from adjustText code, so I don't think I am the person to ask... As I don't get this error myself, you'll have to see where exactly in the code it occurs. Maybe you have a very high/low dpi or figure size set in you rcparams? It seems it has something to do with that.

**Comment by rodrigosantis1** [comment]
Here the notebook:
[Untitled.ipynb.zip](https://github.com/Phlya/adjustText/files/732498/Untitled.ipynb.zip)

I'll try to change the figure size and rcparams, anyway thanks for the fast response and assistance!
