### ISSUE TITLE
Allow force_text and force_points to be tuples with force in x and y directions

### ISSUE THREAD

**Issue by v5364704** [Phlya/adjustText#22]
Nice tool, used it when studied math.
Because text annotations are usually longer along X axis it is sometimes more optimal to distribute them vertically with higher force. For this reason force_text and force_points arguments could be extended to accept both scalar and tuple with x and y forces specified separately. As far as I understand only adjust_text(...) needs modifications when dx and dy are calculated.

**Comment by Phlya** [comment]
That's a good idea, thanks, I'll look into it when I have time! (Or feel free to prepare a PR).

**Comment by Phlya** [comment]
That's a good idea, thanks, I'll look into it when I have time! (Or feel free to prepare a PR).

**Comment by Phlya** [comment]
This is implemented in the latest commit, please check it works as you'd expect.

**Comment by Phlya** [comment]
Just provide a tuple with two floats/ints, for x and y for any of the three forces instead of a float/int (just a number should continue to work as it used to).

**Comment by Phlya** [comment]
I think it works for me, so I'll close the issue.
