### ISSUE TITLE
add link from mpl docs

### ISSUE THREAD

**Issue by tacaswell** [Phlya/adjustText#23]
Can you add a blurb the the upstream docs?  

I think this page  http://matplotlib.org/devdocs/thirdpartypackages/index.html who's source is https://github.com/matplotlib/matplotlib/blob/master/doc/thirdpartypackages/index.rst is a good place to put it.

**Comment by Phlya** [comment]
Thanks for the suggestion! I have just made a PR https://github.com/matplotlib/matplotlib/pull/8362
I'd like to add an image then too, how do I do that?..

**Comment by Phlya** [comment]
Ah, I think I figures it out.
