### ISSUE TITLE
Plot with date/timestamp on the x-axis

### ISSUE THREAD

**Issue by rudolfmayer** [Phlya/adjustText#26]
I have a plot where I have datetime objects on the x axes, and a normal real number on the y axis; your library doesn't work with that, unfortunately, I get 

>   File "/home/XXX/.local/lib/python2.7/site-packages/adjustText/adjustText.py", line 374, in adjust_text
>    orig_xy = [text.get_position() for text in texts]
>AttributeError: 'datetime.datetime' object has no attribute 'get_position'

Is there any way to fix this for datetime?

**Comment by Phlya** [comment]
Thank you for reporting! Could you please provide an example that fails like this?

It definitely works when dates are plotted using matplotlib functionality, for example like here https://github.com/Phlya/adjustText/issues/14, or in the examples https://github.com/Phlya/adjustText/blob/master/examples/Examples.ipynb (cell 14 and downwards).

**Comment by rudolfmayer** [comment]
I have a small demo, but it actually doesn't produce the same error as above..

<pre>
import datetime
import random
import matplotlib.pyplot as plt
from adjustText import adjust_text

# make up some data
x = [datetime.datetime.now() + datetime.timedelta(hours=i) for i in range(12)]
y = [i+random.gauss(0,1) for i,_ in enumerate(x)]

# plot
plt.plot(x,y)

# add labels
texts = []
for x, y, in zip(x, y):
    texts.append(plt.text(x, y, "dummy label for " + str(y), bbox={'pad': 0, 'alpha': 0}, size=10))

adjust_text(texts, x, y, arrowprops=dict(arrowstyle="-", color='k', lw=0.5), bbox={'pad': 0, 'alpha': 0}, size=10)

# beautify the x-labels
plt.gcf().autofmt_xdate()

plt.show()
</pre>

produces
>    adjust_text(texts, x, y, arrowprops=dict(arrowstyle="-", color='k', lw=0.5), bbox={'pad': 0, 'alpha': 0}, size=10)
>  File "/home/xxx/.local/lib/python2.7/site-packages/adjustText/adjustText.py", line 407, in adjust_text
    ax=ax)
>  File "/home/xxx/.local/lib/python2.7/site-packages/adjustText/adjustText.py", line 111, in optimally_align_text
>    c = len(get_points_inside_bbox(x, y, bbox))
>  File "/home/xxx/.local/lib/python2.7/site-packages/adjustText/adjustText.py", line 24, in >get_points_inside_bbox
    x_in = np.logical_and(x>x1, x<x2)
>TypeError: can't compare datetime.datetime to numpy.float64
</PRE>

**Comment by Phlya** [comment]
First of all, here you are renaming x and y in the loop, so adjust_text gets confused. Second, you need to convert dates to numbers and use plot_date - as shown in the examples.
This works:
```
import random
import matplotlib.pyplot as plt
from matplotlib import dates
from adjustText import adjust_text
x = [datetime.datetime.now() + datetime.timedelta(hours=i) for i in range(12)]
y = [i+random.gauss(0,1) for i,_ in enumerate(x)]
x = dates.date2num(x)
plt.plot_date(x,y)
texts = []
for xi, yi, in zip(x, y):
     texts.append(plt.text(xi, yi, "dummy label for " + str(y), bbox={'pad': 0, 'alpha': 0}, size=10))
adjust_text(texts, x, y, arrowprops=dict(arrowstyle="-", color='k', lw=0.5), bbox={'pad': 0, 'alpha': 0}, size=10)
plt.gcf().autofmt_xdate()
plt.show()
```

**Comment by Phlya** [comment]
I think this solves the problem, so I'm closing the issue.
