### ISSUE TITLE
Font size?

### ISSUE THREAD

**Issue by jeiranj** [Phlya/adjustText#30]
Hi,
Hope all is well!

I somehow cant change the font size:

`adjust_text(texts, force_text=(2,2), arrowprops=dict(arrowstyle="-|>", color='k', alpha=0.4), fontsize=60)`

Changing the value of the `fonrsize` arg has no effect.
What is happening? Thanks!

**Comment by Phlya** [comment]
Hi, why don't you specify the fontsize when creating texts?

**Comment by Phlya** [comment]
If you don't, the labels might start overlapping, since their size will be different than the original one.
What you are trying to do doesn't work because (I think) all properties of annotations are updated after creation using the original text objects.

**Comment by jeiranj** [comment]
Perfect! That worked perfectly. Thanks!

**Comment by Phlya** [comment]
Glad I could help!
