### ISSUE TITLE
Seaborn swarmplot flips ylim

### ISSUE THREAD

**Issue by avsastry** [Phlya/adjustText#34]
When using adjust text to annotate a seaborn swarmplot, all the text gets moved to the top of the plot. For example:
```import seaborn as sns
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.swarmplot(x=tips["total_bill"])
for collection in ax.collections:
    points = collection.get_offsets()
    texts = []
    for x,y in points[:10]:
        texts.append(ax.text(x,y,str(x)))
adjust_text(texts)
```

displays 
![seaborn](https://user-images.githubusercontent.com/9089900/32811615-94f08e70-c955-11e7-8173-54558138ae3f.png)

This seems to be because seaborn flips the ylim of the axis, as `ax.get_ylim()` has the larger number first. A temporary workaround is to reset the ylim in the correct order before calling adjust_text (`ax.set_ylim(reversed(ax.get_ylim()))`) which flips the entire plot. A permanent workaround is to check for this on line 295-296 of adjustText.py in `repel_text_from_axes` to ensure that ymin < ymax.

**Comment by Phlya** [comment]
Thank you for reporting this @avsastry! I wonder why seaborn needs to invert the y axis... However adjustText should support inverted axis, and if you can submit a PR for this I would be happy to merge it. Otherwise, I am not sure when I will find time to do this myself, unfortunately.

**Comment by Phlya** [comment]
Hi, this should work as expected now, sorry it took me so long to fix. Please let me know if you still have a problem, otherwise I am closing this.
