### ISSUE TITLE
Does not perform well in 4 subplots of different scales

### ISSUE THREAD

**Issue by shannonnnn** [Phlya/adjustText#36]
Tried to apply this on 4 subplots - scatter plots: 
subplot 1: x-axis: 0-3u; y-axis: 0-3u 
subplot 2: x-axis: 3-4u; y-axis: 0-3u 
subplot 3: x-axis: 0-3u; y-axis: 3-4u 
subplot 4: x-axis: 3-4u; y-axis: 3-4u 

However, it is not working well on the plots. Overlapping issue persists for force_text, force_points and force_objects factor up to 10 and above. Sometimes when it hits a certain value, the text will get repelled suddenly with too big the distance. Please advise. Thanks for your help!

**Comment by Phlya** [comment]
Can you please make a minimal reproducible example?

**Comment by weitingg** [comment]
![scatterplot](https://user-images.githubusercontent.com/6932818/34772412-cedb0664-f642-11e7-890f-5143be1e2bea.png)

Example of the graph is attached here.

**Comment by Phlya** [comment]
With code, please

**Comment by weitingg** [comment]
`import matplotlib.pylab as plt
import adjustText

labels = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9', 'test10', 'test11', 'test12', 'test13', 'test14', 'test15']

x = [4.00, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50]
y = [2.50, 2.55, 2.60, 2.65, 2.70, 2.75, 2.80, 2.85, 2.90, 2.95, 3.00, 3.50, 3.35, 3.25, 3.50]

ax1 = plt.subplot2grid((2,2), (0,0), rowspan=1, colspan=1)
ax2 = plt.subplot2grid((2,2), (0,1), rowspan=1, colspan=1)
ax3 = plt.subplot2grid((2,2), (1,0), rowspan=1, colspan=1)
ax4 = plt.subplot2grid((2,2), (1,1), rowspan=1, colspan=1)

ax1.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax2.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax3.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax4.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)

ax1.set_xlim(0,3)
ax2.set_xlim(3,4)
ax3.set_xlim(0,3)
ax4.set_xlim(3,4)

ax1.set_ylim(3,4)
ax2.set_ylim(3,4)
ax3.set_ylim(0,3)
ax4.set_ylim(0,3)

ax1.plot([3,3],[0,4], linewidth=3, color='black')
ax1.plot([0,4],[3,3], linewidth=3, color='black')
ax2.plot([3,3],[0,4], linewidth=3, color='black')
ax2.plot([0,4],[3,3], linewidth=3, color='black')
ax3.plot([3,3],[0,4], linewidth=3, color='black')
ax3.plot([0,4],[3,3], linewidth=3, color='black')
ax4.plot([3,3],[0,4], linewidth=3, color='black')
ax4.plot([0,4],[3,3], linewidth=3, color='black')

graph=[]

for i, txt in enumerate(labels):
	if(x[i]>=0 and x[i]<=3 and y[i]<=4 and y[i]>3):
		graph.append(ax1.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
try:
	adjustText.adjust_text(graph, ax=ax1,force_text=10 , force_objects=10, force_points=10, expand_points=(10, 10), expand_text=(10,10), expand_objects=(10,10), arrowprops=dict(arrowstyle="->"), wrap=True)
except: 
	print("")

for i, txt in enumerate(labels):
	if(x[i]<=4 and x[i]>3 and y[i]<=4 and y[i]>3):
		graph.append(ax2.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
try:
	adjustText.adjust_text(graph, ax=ax2, force_text=10 , force_objects=10, force_points=10, expand_points=(10, 10), expand_text=(10,10), expand_objects=(10,10), arrowprops=dict(arrowstyle="->"), wrap=True)
except:
	print("")

for i, txt in enumerate(labels):
	if(x[i]>=0 and x[i]<=3 and y[i]>=0 and y[i]<=3):
		graph.append(ax3.text(df.x[i], df.y[i], txt, color='purple',size=8,bbox=dict(boxstyle="square", fc="w", pad=0.2)))
try:
	adjustText.adjust_text(graph, ax=ax3, force_text=10 , force_objects=10, force_points=10, expand_points=(10, 10), expand_text=(10,10), expand_objects=(10,10), arrowprops=dict(arrowstyle="->"), wrap=True)
except:
	print("")

for i, txt in enumerate(labels):
	if(x[i]<=4 and x[i]>3 and y[i]>=0 and y[i]<=3):
		graph.append(ax4.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
try:
	adjustText.adjust_text(graph, ax=ax4, force_text=10 , force_objects=10, force_points=10, expand_points=(10, 10), expand_text=(10,10), expand_objects=(10,10),  arrowprops=dict(arrowstyle="->"))
except:
	print("")

plt.show()`

**Comment by Phlya** [comment]
You need to define new `graph` variable before adding texts to it. And your `try:`-`except:` constructs hid that adjustment didn't work at all and actually raised an error.
```
labels = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9', 'test10', 'test11', 'test12', 'test13', 'test14', 'test15']

x = [4.00, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50, 3.50]
y = [2.50, 2.55, 2.60, 2.65, 2.70, 2.75, 2.80, 2.85, 2.90, 2.95, 3.00, 3.50, 3.35, 3.25, 3.50]

ax1 = plt.subplot2grid((2,2), (0,0), rowspan=1, colspan=1)
ax2 = plt.subplot2grid((2,2), (0,1), rowspan=1, colspan=1)
ax3 = plt.subplot2grid((2,2), (1,0), rowspan=1, colspan=1)
ax4 = plt.subplot2grid((2,2), (1,1), rowspan=1, colspan=1)

ax1.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax2.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax3.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)
ax4.scatter(x, y, c='b', alpha=1, vmin=0, vmax=4, zorder=2)

ax1.set_xlim(0,3)
ax2.set_xlim(3,4)
ax3.set_xlim(0,3)
ax4.set_xlim(3,4)

ax1.set_ylim(3,4)
ax2.set_ylim(3,4)
ax3.set_ylim(0,3)
ax4.set_ylim(0,3)

ax1.plot([3,3],[0,4], linewidth=3, color='black')
ax1.plot([0,4],[3,3], linewidth=3, color='black')
ax2.plot([3,3],[0,4], linewidth=3, color='black')
ax2.plot([0,4],[3,3], linewidth=3, color='black')
ax3.plot([3,3],[0,4], linewidth=3, color='black')
ax3.plot([0,4],[3,3], linewidth=3, color='black')
ax4.plot([3,3],[0,4], linewidth=3, color='black')
ax4.plot([0,4],[3,3], linewidth=3, color='black')

graph=[]

for i, txt in enumerate(labels):
    if(x[i]>=0 and x[i]<=3 and y[i]<=4 and y[i]>3):
        graph.append(ax1.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
adjust_text(graph, ax=ax1, arrowprops=dict(arrowstyle="->"))

graph = []
for i, txt in enumerate(labels):
    if(x[i]<=4 and x[i]>3 and y[i]<=4 and y[i]>3):
        graph.append(ax2.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
adjust_text(graph, ax=ax2, arrowprops=dict(arrowstyle="->"))

graph = []
for i, txt in enumerate(labels):
    if(x[i]>=0 and x[i]<=3 and y[i]>=0 and y[i]<=3):
        graph.append(ax3.text(df.x[i], df.y[i], txt, color='purple',size=8,bbox=dict(boxstyle="square", fc="w", pad=0.2)))
adjust_text(graph, ax=ax3, arrowprops=dict(arrowstyle="->"))

graph = []
for i, txt in enumerate(labels):
    if(x[i]<=4 and x[i]>3 and y[i]>=0 and y[i]<=3):
        graph.append(ax4.text(x[i], y[i], txt, color='purple', size=8, bbox=dict(boxstyle="square", fc="w", pad=0.2)))
adjust_text(graph, ax=ax4, arrowprops=dict(arrowstyle="->"))

plt.show()
```
![image](https://user-images.githubusercontent.com/2895034/34774817-c83fe3d6-f608-11e7-896c-737a818ddb9d.png)
