### ISSUE TITLE
bug with axes being passed in conjunction with Tkinter

### ISSUE THREAD

**Issue by SpyD235** [Phlya/adjustText#37]
While using this together with Tkinter, adjusttext would do funny things to my axis. I found the bug though.
At line 497-8 (I think it's on the newest version) get_bboxes() is missing the ax=ax argument and so it uses plt.gca() instead.
            move_texts(texts, dx, dy,
                       bboxes = get_bboxes(texts, r, (1, 1)), ax=ax)

I changed it on my side and it fixed the problem working with Tkinter

**Comment by Phlya** [comment]
Cool, thank you for reporting! Do you mind submitting a PR with this change?

**Comment by SpyD235** [comment]
I don't know what a PR is. I just signed up to GitHub to report this.

**Comment by Phlya** [comment]
PR is a pull request. https://help.github.com/articles/about-pull-requests/
It is used for me to accept changes suggested by other people without manually introducing them myself and to keep track of who made the change. If you don't want to do it (although for such a small change it's trivial, you can just edit the files online), I can introduce it myself, of course.

**Comment by Phlya** [comment]
So, I hope I fixed this now - the line number was a bit different. Could you please check the newest version? @SpyD235
