### ISSUE TITLE
type error at end of ajust_text

### ISSUE THREAD

**Issue by EisFranzi** [Phlya/adjustText#42]
I was trying your examples. Everything worked well except at the end I get the error:

  File "C:\Python27\lib\site-packages\adjustText\adjustText.py", line 563, in adjust_text
    return i+1
TypeError: can only concatenate tuple (not "int") to tuple

This actually prevents the image from being saved with a plt.savefig() command. 
I did not install pandas. Is that a prerequisite?

Thanks for paying attention!

**Comment by Phlya** [comment]
Hi, thanks for your interest and for reporting this. Could you please share
the exact code you used?

вт, 17 Апр 2018 г., 9:39 EisFranzi <notifications@github.com>:

**Comment by EisFranzi** [comment]
I tried some examples from https://github.com/Phlya/adjustText/wiki and just added a save command at the end. The image does not get saved because of the error message mentioned before.

import matplotlib.pyplot as plt
from adjustText import adjust_text
import numpy as np

np.random.seed(0)
x, y = np.random.random((2,30))
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')
texts = [plt.text(x[i], y[i], 'Text%s' %i, ha='center', va='center') for i in range(len(x))]
adjust_text(texts)
plt.savefig('C:/Users/nehring/Desktop/Austausch/test.png')_

**Comment by Phlya** [comment]
I'm closing this as fixed by @colinmorris, let me know if it isn't. Thanks!

**Comment by aqshaw** [comment]
Hi

I've been having a similar issue, even without a save command, and when save_steps = False.

I get a type error when running the following code:
>>>
x, y = np.random.random((2,30))
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')
texts = [plt.text(x[i], y[i], 'Text%s' %i, ha='center', va='center') for i in range(len(x))]
adjust_text(texts,save_steps = False)
plt.show()

**Comment by aqshaw** [comment]
Hi.

I did try, but I had another go. This time I uninstalled the PyPl first, and then installed from the repo. That seems to have done it.

Sorry to take up your time on something silly.

Thanks
