### ISSUE TITLE
adjust_text stops moving texts one step before reaching the desired precision

### ISSUE THREAD

**Issue by colinmorris** [Phlya/adjustText#45]
See [line 532 in adjustText.py](https://github.com/Phlya/adjustText/blob/4a43bf30ae785111900076ea20ffb156189e6f2f/adjustText/adjustText.py#L532). When we reach the desired precision, we break out of the loop without actually calling `move_texts`.

**Comment by Phlya** [comment]
You are right, again! Do you want to fix this yourself, or should I?

**Comment by Phlya** [comment]
This is also fixed now, I believe.
