### ISSUE TITLE
In optimally_align_text, we shouldn't consider a text's overlap with itself

### ISSUE THREAD

**Issue by colinmorris** [Phlya/adjustText#46]
In [this line](https://github.com/Phlya/adjustText/blob/4a43bf30ae785111900076ea20ffb156189e6f2f/adjustText/adjustText.py#L128), when calculating the overlaps of text `t` using alignment `a`, we're including the size of the overlap with `t` itself, as originally placed.

One undesirable effect of this is that, if there are several alignments that don't overlap any points or fall outside the axes, we'll prefer the one that is *most different* from the original alignment, because it will have the least self-intersection. e.g. if the user originally chose to place their texts with ha=left, va=bottom, we'll prefer to change it to ha=right, va=top.

**Comment by Phlya** [comment]
Cool, I have noticed weird behavior which probably has to do with this issue, but haven't managed to figure out what was going on! As with other issues, this should be very easy to fix, would you like to do it yourself?

**Comment by Phlya** [comment]
I think this has been fixed.
