### ISSUE TITLE
Nice-to-have: all else being equal, prefer the passed in values of ha and va in optimally_align_text

### ISSUE THREAD

**Issue by colinmorris** [Phlya/adjustText#48]
If there are many ways a text can be aligned without creating any overlaps, it would be nice to break ties by choosing the values of `ha` and `va` passed to `adjust_text`.

Because of #46, the current behaviour is basically the opposite of this - `optimally_align_text` will prefer alignments that are as different as possible from `ha` and `va`.

**Comment by Phlya** [comment]
Mmm yse, I guess you are right, however I was just thinking that if autoalignment is not restricted, then it just overrides `ha` and `va`... Which may of course not be obvious from the description.

**Comment by colinmorris** [comment]
Yeah, I understand that with autoalignment on, we can no longer make any guarantees about respecting `ha` and `va`. But if we have a bunch of potential alignments that work equally well and have to choose among them arbitrarily, this just seems like a nice way to do it.
