### ISSUE TITLE
Not working with seaborn jointplot

### ISSUE THREAD

**Issue by nickwan** [Phlya/adjustText#54]
When trying to use seaborn's text I've ran into really strange issues. Unsure if they are related to any of the previous seaborn issues (it didn't seem so)

Here's a notebook with the issue 
https://github.com/nickwan/adjustText_jointplot/blob/master/adjustText_jointplot.ipynb

I'm able to plot text labels no problem with the seaborn function. I try using a regular for loop like in the adjustText docs and get this really tiny figure. I try it again, this time accessing the texts through the figure and (no surprise) I get the same issue. 

I don't think I'm skipping a step? Would really like to get this to work!

**Comment by Phlya** [comment]
Hi,

You need to specify the axes object - `plt.gca()` must be returning one of the side axes and this leads to some unpredictable behaviour. And in general you should do this when working with multiple subplots to prevent unexpected problems.

So, doing this
`adjust_text(texts, ax=h.ax_joint)`

Gives this
![image](https://user-images.githubusercontent.com/2895034/41296050-e9a3191c-6e53-11e8-8281-510655c09ce8.png)
