### ISSUE TITLE
Not working properly with pyplot.imshow

### ISSUE THREAD

**Issue by hennumea** [Phlya/adjustText#55]
I'm trying to annotate a picture (numpy 2D array) using pyplot.imshow, but adjust_text is not very successful. It seems to place the texts outside the axes limits nor does it handle the overlapping well 

I'm running Python 3.6.1, matplotlib 2.2.2, adjusttext 0.7.2.

Example code:

```python
import numpy as np
import matplotlib.pyplot as plt
from adjustText import adjust_text

img = np.random.randint(low=0, high=10, size=(100, 100))
xr = np.random.randint(low=10, high=90, size=5)
yr = np.random.randint(low=10, high=90, size=5)

fig = plt.figure()
ax = fig.add_subplot(111)
ax.imshow(img, cmap='Greys', vmax='100')
texts = [plt.text(x, y, s='text here', color='red', fontsize=16) for x, y in zip(xr, yr)]
adjust_text(texts, arrowprops=dict(arrowstyle='-', color='red'))
plt.show()
````

**Comment by Phlya** [comment]
Hi, thanks for reporting this - interesting, I have never tried annotating
an image. Can you try adding the on_basemap argument? Possibly it's the
same problem there?..

**Comment by hennumea** [comment]
I have tried switching 'on_basemap' argument, but no difference. An alternative for me is to use pyplot.pcolormesh, where adjust_text seems to work fine, but that means that I have to rewrite a good chunk of code.

pyplot.imshow places the origin of the image at the top by default, because most images (as with the ultrasound images I'm trying to annotate) are scanned from top to bottom (same with image sensors, I guess). I assume that it have something to do with how the axes are handled which confuses adjust_text.

**Comment by Phlya** [comment]
Ah, right! Inverted axes are a problem, can you just change that manually
to check whether this is the problem?

**Comment by Phlya** [comment]
Thanks, good, then this is not a new issue, and there is a workaround for
now.

It should not be difficult to make it work for inverted axes, I just
haven't found the time yet to do this.

**Comment by Phlya** [comment]
I'll close this since it has already been reported to multiple times - but really need to get this working!
