### ISSUE TITLE
how to work with adjustText with multiple subplots?

### ISSUE THREAD

**Issue by zyxue** [Phlya/adjustText#58]
I cannot make it work well with the following code patterns

1. adjust text for each subplot
```
fig, axes = plt.subplots(2, 2, figsize=(14, 12))
axes = axes.ravel()

for k, ax in enumerate(axes):
    # do some plotting
    texts = []
    # collect texts in a for loop
    # call adjust_text
```

2. adjust text for texts in all subplots together
```
fig, axes = plt.subplots(2, 2, figsize=(14, 12))
axes = axes.ravel()

texts = []
for k, ax in enumerate(axes):
    # do some plotting
    # collect texts in a for loop

# call adjust_text
```

What's the right way to do it? I haven't made it work in either case yet.

**Comment by Phlya** [comment]
Hi,

The first option is correct. However make sure you also use the ax=ax
argument in adjust_text. Let me know if this helps.

Best,
Ilya

**Comment by zyxue** [comment]
Thanks, I will try it out. BTW, will `ax.set_xlim` or `ax.set_ylim` have an effect on adjustText? I saw some strange behavior before.

**Comment by Phlya** [comment]
Yes, always call adjust_text after changing axes limits.

**Comment by Phlya** [comment]
@zyxue did this solve your problems?

**Comment by zyxue** [comment]
I've made an example at , https://github.com/zyxue/adjustText/blob/master/figures/Examples-for-multiple-subplots.ipynb. 

Also, it seems to be much slower than in a single-subplot case (17.9 ms vs 13.4 s).

**Comment by Phlya** [comment]
As I mentioned above, you have to add `ax=ax` to adjust_text call:

```python
fig, axes = plt.subplots(1, 2, figsize=(8, 3), sharex=True, sharey=True)
axes = axes.ravel()

for k, ax in enumerate(axes):
    np.random.seed(0)
    x, y = np.random.random((2,30))
    ax.plot(x, y, 'bo')

    texts = []
    for i in range(len(x)):
        t = ax.text(x[i], y[i], 'Text%s' %i, ha='center', va='center')
        texts.append(t)
    adjust_text(texts, ax=ax)
```

![image](https://user-images.githubusercontent.com/2895034/43050232-d69f61b6-8e0d-11e8-9134-73bdae0ef13c.png)

**Comment by zyxue** [comment]
Ah I see. I didn't fully get that. Ok, I will try it out later and let you know. Thank you!

**Comment by zyxue** [comment]
I don't fully understand what you mean by "If they are slightly smaller in one case, it can slow down the execution considerably". 

I have updated my notebooks, why the time spent is so different for adjusting the first and second subplots, please?

```
CPU times: user 11.7 s, sys: 236 ms, total: 12 s
Wall time: 12 s
CPU times: user 2.52 s, sys: 57.8 ms, total: 2.57 s
Wall time: 2.58 s
```

BTW, are you interested in a pull request, I thought having a such an example for multiple subplots would be helpful to other users. It's a very useful package, thank you for sharing it.

**Comment by Phlya** [comment]
Oh, I see. Interesting, I don't know why that is so different, for some reason it does a very different number of iterations each time! I'll try to investigate when I have time...
![screenshot from 2018-07-23 00-51-49](https://user-images.githubusercontent.com/2895034/43050513-9ea0fad6-8e12-11e8-8ccd-5c106921b203.png)

**Comment by Phlya** [comment]
Yeah, would be great to add an example about this, you are not the first person to ask this question!

**Comment by zyxue** [comment]
ok, I've sent a pull request. Not I also removed `figures/.ipynb_checkpoints` from the commit as it's in your `.gitignore`  already.

**Comment by zyxue** [comment]
Reopen because the time discrepancy for different subplots hasn't been resolsoved

Quote a previous comment:
```
CPU times: user 11.7 s, sys: 236 ms, total: 12 s
Wall time: 12 s
CPU times: user 2.52 s, sys: 57.8 ms, total: 2.57 s
Wall time: 2.58 s
```
