### ISSUE TITLE
AttributeError: 'Bbox' object has no attribute 'intersection'

### ISSUE THREAD

**Issue by leefangu** [Phlya/adjustText#60]
I did not installed the package since I don't have the privilege to install any packages on our server . So I copied all the code to my project. However, I am not able to call adjust_text function. I am getting below error all the time:
AttributeError: 'Bbox' object has no attribute 'intersection'

Please help and thank you so much.
Frank

**Comment by leefangu** [comment]
import matplotlib
matplotlib.use('Agg')
from adjustText import *
import numpy as np

np.random.seed(0)
x, y = np.random.random((2,30))
fig, ax = plt.subplots()
plt.plot(x, y, 'bo')
texts = [plt.text(x[i], y[i], 'Text%s' %i, ha='center', va='center') for i in range(len(x))]
adjust_text(texts)


The above code is saved in a file named test.py on the company's server in the folder /home/p57400/ERSSatisfaction/code/. I then executed the code using below command:
 /usr/hdp/2.5.3.0-37/spark/bin/spark-submit /home/p57400/ERSSatisfaction/code/test.py
And below is the error I got after I executed it:

Traceback (most recent call last):
  File "/home/p57400/ERSSatisfaction/code/test.py", line 11, in <module>
    adjust_text(texts)
  File "/home/p57400/ERSSatisfaction/code/adjustText.py", line 424, in adjust_text
    ax=ax)
  File "/home/p57400/ERSSatisfaction/code/adjustText.py", line 125, in optimally_align_text
    bboxes+add_bboxes]
AttributeError: 'Bbox' object has no attribute 'intersection'

**Comment by leefangu** [comment]
can you please check your matplotlib version? I am thinking my version (which is 1.2.0) is too old to have intersection function. You can use below commands to find out the version:

import matplotlib
matplotlib.__version__

**Comment by Phlya** [comment]
Wow 1.2??? Yeah, mine is 2.2.2, that's is probably the problem. 1.2 is a very old version!

**Comment by leefangu** [comment]
I upgraded matplotlib to 2.2.3 and now it is good. Thank you for the great package!!

**Comment by Phlya** [comment]
Great, thanks for letting me know!
