### ISSUE TITLE
Confusing explanation/example for only_move parameter

### ISSUE THREAD

**Issue by colinmorris** [Phlya/adjustText#61]
only_move (dict): a dict to restrict movement of texts to only certain
            axis. Valid keys are 'points', 'text', and 'objects'. For each of
            them valid values are 'x', 'y' and 'xy'. This way you can forbid
            moving texts along either of the axes due to overlaps with points,
            but let it happen if there is an overlap with texts:
            only_move={'points':'y', 'text':'xy'}. Default: everything is allowed.

Does `only_move={'points':'y', 'text':'xy'}` really mean forbid moving text along either axis due to overlaps with points? Or should it be `only_move={'points':'', 'text':'xy'}`?

And if so, shouldn't we say:

> valid values are 'x', 'y', 'xy' **and ''**

**Comment by Phlya** [comment]
Mhhh yeah right, thank you for reporting this! I think this is a mistake in the docs. Indeed your correction is right on both points. Would you like to make a quick PR to fix this?
