### ISSUE TITLE
never ends on very large dataset

### ISSUE THREAD

**Issue by simo1994** [Phlya/adjustText#66]
Hello,
I'm trying to use adjustText on a very large graph, `figsize=[200,200]`, with about 10k points/text labels.
I tried configuring it with lim=1 and giving it a very large amount of precision, but it still looks like it's never going to end processing (I gave up after 8+ hours on 8th gen i7).
Am I interpreting the parameters wrong, or adjustText just isn't intended to run with 10k labels?

`adjust_text(plot_texts, lim=1, precision=10E9, arrowprops=dict(arrowstyle="->", color='r', lw=0.5))`

Thanks in advance.

**Comment by Phlya** [comment]
Hi. The limiting step for so many data points is autoalignment, if you
switch it off it should work - although it will be slow anyway. Let me know
if this helps!

**Comment by Phlya** [comment]
Also, check out this, Santosh contacted me earlier about the same problem:
https://github.com/Santosh-Gupta/Lit2Vec

**Comment by Phlya** [comment]
https://lmcinnes.github.io/subreddit_mapping/
Also you might be interested in this approach.
