### ISSUE TITLE
Draggable keyword argument?

### ISSUE THREAD

**Issue by skoeb** [Phlya/adjustText#69]
Thanks for a great package!

I remember using this a few months ago and still being able to easily access the `.draggable()` method of annotations to be able to interactively move them (sometimes even adjustText gets one or two wrong!)

However revisiting this package now, I can't find this anywhere and get an AttributeError when trying things like `draggable = True`. A breadcrumb is in #68, which has 'draggable' as a keyword argument in some of the pasted code. Am I imagining this, or did this used to be a functionality?

**Comment by Phlya** [comment]
Hi, you are right, I completely forgot about it... I've slightly changed
the way annotations are created now (basically, it doesn't create a whole
annotation object, but just draws an arrow from the text to the point), so
it can't work anymore, sorry. But in general, the dragging was really
buggy, unless matplotlib guys have fixed it by now... I think I reported
the bug at some point, but I'm away from my computer at the moment.

**Comment by skoeb** [comment]
That makes sense, I was searching through the ax.children created by adjustText and was unable to manually make those draggable too. I agree draggable objects in matplotlib are buggy! 

Thanks, I'll keep using adjustText for plots that have a high number of labels, but just place them manually and drag if there are fewer labels with critical positions.
