### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by phue** [Phlya/adjustText#75]
Hi,

do you plan on adding adjustText to the conda-forge channel?

I'm asking because I'm currently trying to add a recipe for https://github.com/limix/limix-plot which depends on adjustText and conda-forge requires every dependency to be packaged there. If you don't mind I can also submit a recipe for adjustText.

**Comment by Phlya** [comment]
Hi,

Cool, feel free to submit a PR for this! I don't know how to make one, that's the only reason I haven't made a recipe.

**Comment by phue** [comment]
It's now available from conda-forge :rocket: 
https://github.com/conda-forge/adjusttext-feedstock

**Comment by Phlya** [comment]
Brilliant, thanks!
