### ISSUE TITLE
Repel away from the point's circle edge for large points

### ISSUE THREAD

**Issue by MaxGhenis** [Phlya/adjustText#76]
Is there a way to consider the size of the point when adjusting the text? Currently the labels can overlap with the point, e.g. ([notebook](https://colab.research.google.com/drive/1iLS_SuGLtfkilnADPxkdVoJ1CZJayO-L)):
```
import seaborn as sns
import matplotlib.pyplot as plt
from adjustText import adjust_text

tips = sns.load_dataset("tips").head(20)

def plot_scatter(adjust):
    ax = sns.scatterplot(x="total_bill", y="tip", size="size", sizes=(0, 1000), 
                         data=tips)
    texts = [plt.text(row.total_bill, row.tip, row.day)
             for index, row in tips.iterrows()]
    if adjust:
        adjust_text(texts)
        
plot_scatter(False)
```
![image](https://user-images.githubusercontent.com/6076111/53707705-e6786b00-3de4-11e9-8228-140606b9fb47.png)

```
plot_scatter(True)
```
![image](https://user-images.githubusercontent.com/6076111/53707707-e9735b80-3de4-11e9-83ff-6a5c7ed9bf19.png)

**Comment by Phlya** [comment]
Hi,

It's not possible, unfortunately - however you can repel from their bounding boxes using `add_objects`.

**Comment by MaxGhenis** [comment]
Looking through the second `add_objects` example in [Examples.ipynb](https://github.com/Phlya/adjustText/blob/master/docs/source/Examples.ipynb) it looks like I could pass it a list of [`patches.Circle`](https://matplotlib.org/api/_as_gen/matplotlib.patches.Circle.html#matplotlib.patches.Circle) objects for each of the points, where `radius~size`, is that right?

**Comment by Phlya** [comment]
Yes. It might work with the actual output of scatter though?.. I think I tried it in the past, but I forgot whether it works or not.

**Comment by MaxGhenis** [comment]
Not sure how to use the output directly, but extracting the point sizes to create `Circle`s didn't seem to quite work. Multiplying the radius by 10 gave a different result though, so seems like there's something there.
```
def plot_scatter(add_patch, radius_multiplier=1):
    ax = sns.scatterplot(x="total_bill", y="tip", size="size", sizes=(20, 1000), 
                         data=tips)
    texts = [plt.text(row.total_bill, row.tip, row.day)
             for index, row in tips.iterrows()]
    # Get radius of each point: get_sizes() returns area.
    radii = np.sqrt(ax.get_children()[0].get_sizes() / np.pi)
    patch = [patches.Circle((row.total_bill, row.tip), 
                            radii[index] * radius_multiplier)
             for index, row in tips.iterrows()]
    if add_patch:
        adjust_text(texts, add_objects=patch)
    else:
        adjust_text(texts)
    plt.show()
        
plot_scatter(add_patch=False)
```
![Adjusted plot without patches](https://user-images.githubusercontent.com/6076111/53752971-ee77ef80-3e64-11e9-9220-991c613acc3d.png)

    plot_scatter(add_patch=True)

![Adjusted plot with patches](https://user-images.githubusercontent.com/6076111/53752995-ff286580-3e64-11e9-945d-42ca1bbf46ee.png)

    plot_scatter(add_patch=True, radius_multiplier=10)

![Adjusted plot with patches scaled by 10x radius](https://user-images.githubusercontent.com/6076111/53753028-0d768180-3e65-11e9-8bd5-2b8273316779.png)

**Comment by Phlya** [comment]
I think in matplotlib radius of the circle is actually proportional to squared size argument... Maybe?.. I have a feeling there was something like that going on.

**Comment by Phlya** [comment]
Two ideas.

First, you need to actually add the patches to the axes for this to work properly.
Second, you need to use Ellipses or do something about the Circles transforms, since simply drawn like this Circles will get distorted according to the scale of the axes. I.e. see below, adjust_text works, but getting the right objects is tricky.

```
tips = sns.load_dataset("tips").head(20)

def plot_scatter(add_patch, radius_multiplier=1):
    ax = sns.scatterplot(x="total_bill", y="tip", size="size", sizes=(20, 1000), 
                         data=tips)
    texts = [plt.text(row.total_bill, row.tip, row.day)
             for index, row in tips.iterrows()]
    # Get radius of each point: get_sizes() returns area.
    radii = np.sqrt(ax.get_children()[0].get_sizes() / np.pi)
    patch = [patches.Circle((row.total_bill, row.tip), 
                            radii[index] * radius_multiplier)
             for index, row in tips.iterrows()]
    for p in patch:
        ax.add_patch(p)
    if add_patch:
        print(adjust_text(texts, add_objects=patch))
    else:
        adjust_text(texts)
    plt.show()
```
![image](https://user-images.githubusercontent.com/2895034/53764947-9bcf1f80-3ec6-11e9-9875-c27ae44b0d86.png)

**Comment by Phlya** [comment]
https://stackoverflow.com/questions/55005272/get-bounding-boxes-of-individual-elements-of-a-pathcollection-from-plt-scatter
Let's see

**Comment by Phlya** [comment]
Please try the new version on github!
```tips = sns.load_dataset('tips')[:20]
f, ax = plt.subplots()
ax = sns.scatterplot(x="total_bill", y="tip", size="size", sizes=(10, 1000), 
                        data=tips)
texts = [plt.text(row.total_bill, row.tip, row.day)
         for index, row in tips.iterrows()]
adjust_text(texts, add_objects=ax.get_children()[0], 
            arrowprops=dict(arrowstyle='->', color='red'))
```

![image](https://user-images.githubusercontent.com/2895034/53878301-6c71fd00-4003-11e9-9958-f92dbf9a10b1.png)

**Comment by Phlya** [comment]
It's quite slow, but with lim=100 works the same, to speed it up.

**Comment by Phlya** [comment]
So while it's not repelling from the edge of the circle, but from the bounding box, I'll close the issue, feel free to reopen if something is not right.

**Comment by MaxGhenis** [comment]
Back to #77, do you know if there's a way to only extract the relevant points to pass to `add_objects`? It's repelling from the gray ones too.
![image](https://user-images.githubusercontent.com/6076111/53898318-b00d3c80-3fec-11e9-940a-5c0c9c0a8983.png)

`ax` is constructed as (`scatter` is a wrapper for `sns.scatterplot`):
```
ax = scatter(x, y, False)
scatter(x, y, True)
```
So I'm looking to just get the points associated with the second line.

**Comment by Phlya** [comment]
You'd have to use the function from the SO answer and only get the bboxes for paths of the right color in there, and then again create fake objects with the right bboxes. Or do scatter calls separately for each color to get them in separate objects.

**Comment by mdandreadtu** [comment]
Hi, I have the same issue as @MaxGhenis.  I tried to run the example code but it doesn't work anymore. It says "ValueError: Can't get bounding boxes from add_objects - is' it a flat list of matplotlib objects?". 
Do you know what has been changed since the time of the answer?

**Comment by Phlya** [comment]
For me the latest version doesn't give an error, but doesn't actually repel from scatter points anymore, I'll investigate, thanks.

**Comment by Phlya** [comment]
Can you please check the latest version on github?

**Comment by mdandreadtu** [comment]
Thanks for your help :) 
I installed the latest version from Github, the example posted above works. 
In my graph, it does work for some points, but in busy areas, it fails and some labels are completely over the scatter point.  
![eo](https://user-images.githubusercontent.com/51364710/86131313-cbeff800-bae5-11ea-86c8-a0094367558f.png)

**Comment by Phlya** [comment]
This doesn't look too bad to me, only a couple overlaps I think. You can play with parameters to make it better, but this is not a silver bullet and sometimes can fail.

**Comment by mdandreadtu** [comment]
Sure, which one is more influencing in your idea? the precision and the number of iteration or 'force_text', 'force_points' , 'force_objects'?

**Comment by Phlya** [comment]
Usually changing the forces is key.

вт, 30 июн. 2020 г. в 14:39, mdandreadtu <notifications@github.com>:

**Comment by mdandreadtu** [comment]
Super! Thanks again for your help and for this amazing package !! :)
