### ISSUE TITLE
Strange issue when labeling stacked points

### ISSUE THREAD

**Issue by MaxGhenis** [Phlya/adjustText#77]
I'm overlapping two scatterplots and using `adjust_text` to label one of the sets of points. While it improves it a lot, it's still giving odd results in my opinion (code below).

Before:
![image](https://user-images.githubusercontent.com/6076111/53708623-27727e80-3de9-11e9-915a-ce7252dc9f9f.png)

After:
![image](https://user-images.githubusercontent.com/6076111/53708626-2ccfc900-3de9-11e9-8339-e9bf4d02106c.png)

In particular, I wasn't sure why El Salvador's label is so far from the point. I thought it might have had to do with the label trying to avoid the gray points also (does it do this?), so tried to add the adjusted text between adding the blue and gray points, but this got messed up, presumably because the gray points change the axis layout.
![image](https://user-images.githubusercontent.com/6076111/53708743-baabb400-3de9-11e9-8771-459988863308.png)

I tried a simpler example ([notebook](https://colab.research.google.com/drive/1Y5-VwQ4Byik8gmctmk6jjpriv_p8pHxC#)) to see if the adjustment incorporates the unlabeled points, and it doesn't like it does (the labels are in similar locations whether they're there or not):
```
import seaborn as sns
import matplotlib.pyplot as plt
from adjustText import adjust_text

tips = sns.load_dataset("tips").sample(20, random_state=0)
smokers = tips[tips.smoker == "Yes"]
nonsmokers = tips[tips.smoker == "No"]

def plot_scatter(adjust, plot_nonsmokers):
    if plot_nonsmokers:
        sns.scatterplot(x="total_bill", y="tip", s=100, color="gray",
                             data=nonsmokers)
    sns.scatterplot(x="total_bill", y="tip", color="blue", s=100,
                    data=smokers)
    texts = [plt.text(row.total_bill, row.tip, index)
             for index, row in smokers.iterrows()]
    if adjust:
        adjust_text(texts)

plot_scatter(adjust=True, plot_nonsmokers=True)
```
![image](https://user-images.githubusercontent.com/6076111/53708883-46254500-3dea-11e9-958b-65fbf1f26e53.png)
```
plot_scatter(adjust=True, plot_nonsmokers=False)
```
![image](https://user-images.githubusercontent.com/6076111/53708887-49b8cc00-3dea-11e9-81b4-9e122aedbfca.png)

Given this, any idea what's going on with the El Salvador label? Thanks.

--code--
```
def scatter(x, y, is_target):
    return sns.scatterplot(x=x, y=y, size='pop', color=PALETTE[is_target],
                           sizes=(min_size[is_target], max_size[is_target]),
                           data=country[country.is_target == is_target],
                           alpha=ALPHAS[is_target])

def chart(x, y, adjust=True):
    # Start with highlighted points, then add adjust_text, then add
    # gray points, then add blue ones again to put them on top.
    ax = scatter(x, y, False)
    scatter(x, y, True)

    texts = [plt.text(row[x], row[y], row.country, size=10, color=PALETTE[True])
             for index, row in country[country.is_target].iterrows()]
    if adjust:
        adjust_text(texts,
                    arrowprops=dict(arrowstyle='->', color=PALETTE[True]))
    
    ax.get_xaxis().set_major_formatter(
        mpl.ticker.FuncFormatter(lambda x, p: format(int(x), ',') + '%'))

    if y == 'gdppcppp':
        ax.get_yaxis().set_major_formatter(
            mpl.ticker.FuncFormatter(lambda x, p: '$' + format(int(x), ',')))
        
    if (y == 'lfpr') or (y == 'lfpr1564'):
        ax.get_yaxis().set_major_formatter(
            mpl.ticker.FuncFormatter(lambda x, p: format(int(x), ',') + '%'))
    
    ax.set(xlabel=title_labels[x] + ' (' + str(latest_year(x)) + ')',
           ylabel=title_labels[y] + ' (' + str(latest_year(y)) + ')')

    plt.title(title_labels[x] + ' vs. ' + labels[y], 
              loc='left')

    ax.grid(color='#f5f5f5')

    ax.text(country[x].max(), country[y].min(), '@MaxGhenis',
            horizontalalignment='right', size=8, color=PALETTE[False])

    sns.despine(left=True, bottom=True)
    ax.get_legend().remove()
    plt.show()

chart('lfpr', 'lfpr1564', False)
chart('lfpr', 'lfpr1564', True)
```

**Comment by Phlya** [comment]
To me it looks normal, to be honest. Algorithm such as the one used in `adjustText` can't always give the perfect result... It's probably a bit further away because it was overlapping a lot with Costa Rica in the beginning. Can you try reducing the force and/or `expand_text`/`expand_points`? This should help to reduce the gaps.

It will not repel from the points that are not specified.

**Comment by MaxGhenis** [comment]
Thanks, here's what it looked like with
```
expand_points=(1.05, 1.05), expand_text=(1.05, 1.05),
force_text=(0.01, 0.01), force_points=(0.01, 0.01), force_objects=(0.01, 0.01))
```
![image](https://user-images.githubusercontent.com/6076111/53754006-85de4200-3e67-11e9-8726-892bdd356234.png)

I think if I can figure out #76 to repel more from the US point I'll be all set.
