### ISSUE TITLE
kwargs for annotate() have no effect

### ISSUE THREAD

**Issue by Khris777** [Phlya/adjustText#8]
I'm giving kwargs to `adjust_text` to be passed to `annotate`, they have no effect at all. There is no error or anything, they are simply ignored. 

Sample code:

	import matplotlib.pyplot as mpp
	import pandas as pd
	import numpy as np
	from adjustText import adjust_text

	df = pd.DataFrame({'A':np.random.rand(20),'B':np.random.rand(20)})
	fig, axes = mpp.subplots(1,1)

	texts = []
	for xt, yt, s in zip(df.B, df.A, df.A):
		texts.append(mpp.text(xt, yt, s))

	kwargs = {'fontsize':'x-small','style':'italic'}

	adjust_text(texts, ax=axes **kwargs)
	fig.show()

Tried different fontsizes and styles, am I doing something wrong?

**Comment by Phlya** [comment]
Hi, can you try setting these parameters in the text objects before adjusting them? I think the reason is probably because I update properties of annotations after they are created using properties if the text object. But I'm not at a computer right now and can't check myself.

**Comment by Phlya** [comment]
Hi, can you try setting these parameters in the text objects before
adjusting them? I think the reason is probably because I update properties
of annotations after they are created using properties if the text object.
But I'm not at a computer right now and can't check myself.

21 Окт 2016 г. 12:45 пользователь "Khris777" <notifications@github.com>
написал:

**Comment by Khris777** [comment]
Doing

    for i in range(len(fig.axes[0].texts)):
        fig.axes[0].texts[i].set_fontsize(10)

before calling `adjust_text` works fine. The text has the correct size and is adjusted with respect to the size.

**Comment by Phlya** [comment]
OK, thanks, good! I should mention this somewhere.
Also it makes much more sense to set this to the text objects initially, because their size influences how they will be adjusted, so if you change the text size in the annotations they might start overlapping.

**Comment by jolespin** [comment]
Has this been fixed?

**Comment by Phlya** [comment]
What exactly? args and kwargs should be passed to `ax.annotate`, but only those affecting the connecting arrow will do anything. All text properties should be applied to the original text objects when creating them.

**Comment by jolespin** [comment]
Oh ok so it preserves those? Nice, that makes a lot of sense. 

So it would be something like this in the example above? 

```
kwargs = {"fontsize":15}
for xt, yt, s in zip(df.B, df.A, df.A):
    texts.append(mpp.text(xt, yt, s, **kwargs))
```

**Comment by Phlya** [comment]
Yep, everything should be preserved!
