### ISSUE TITLE
Similar arrow length

### ISSUE THREAD

**Issue by mja21** [Phlya/adjustText#81]
Hi,

I am using your library to create annotating texts with arrows as shown in the image. 
However, I am always getting different arrow lengths. 
Is there a way to make all the arrows have similar lengths (as for point 1 and 2)?
I've attached the code to generate this sample below.
Thanks for your great work.

![image](https://user-images.githubusercontent.com/37543918/59327742-bba68880-8cea-11e9-8516-69a0353220fa.png)

```
import numpy as np
import matplotlib.pyplot as plt

from adjustText import adjust_text

# Data
x = np.array([0.016696, 4.002370, -3.779990, -7.909700])
y = np.array([-0.08099, 7.15271, 13.02270, 5.10550])


# Plot data
fig, ax = plt.subplots()
ax.plot(x, y, marker='o', markersize=5, color='orange', lw=2)

# Plot texts
texts = []
for i in range(len(x)):
    text = plt.text(x[i], y[i], i, 
                    color='black', ha='center', va='center',
                    bbox=dict(boxstyle="round", ec='orange', fc='w'))
    texts.append(text)


# Format plot
ax.set_xlim(-15, 15)
ax.set_ylim(-6, 20)
ax.set_aspect('equal', adjustable='box')


# Calculate points on line for adjust text
points_on_line_x = np.array([])
points_on_line_y = np.array([])
from scipy import interpolate
for i in range(len(x) - 1):
    x_ = [x[i], x[i+1]]
    y_ = [y[i], y[i+1]]
    l = np.linalg.norm(np.array([[x_[0] - x_[1]], 
                                [y_[0] - y_[1] ]]))
    f = interpolate.interp1d(x_, y_)
    x_lin = np.linspace(min(x_), max(x_), int(l*5))
    points_on_line_x = np.append(points_on_line_x, x_lin)
    points_on_line_y = np.append(points_on_line_y, f(x_lin))

ax.plot(points_on_line_x, points_on_line_y, color='r', marker='o', markersize=0.25, lw=0)


# Adjust text
from adjustText import adjust_text
adjust_text(texts, 
            x=points_on_line_x, y=points_on_line_y,
            expand_points=(3, 2.75), 
            expand_text=(1.05, 1.2), 
            expand_align=(1.05, 1.2),
            force_points=(.2, .3),
            arrowprops=dict(arrowstyle='simple', color='grey', linewidth=0.1))
plt.show()
```

**Comment by Phlya** [comment]
Hi, thank you for using adjustText. I am afraid this is one of the limitations of this approach, and getting arrow lengths identical is impossible. If your plots are as simple as in this example, you can try to only use autoalignement and switch off all repelling (i.e. avoid_text=False, avoid_points=False) - it then should just place labels right next to the points with minimal overlap.

**Comment by mja21** [comment]
Thanks for your quick reply.
Can you explain where the different arrow length in the example comes from?
Does it depend on the number of points in the proximity of the text?

**Comment by Phlya** [comment]
Yes, exactly - if you don't have the points along the lines it should hopefully maintain the distance.

**Comment by Phlya** [comment]
I'll close this, feel free to reopen if you have further issues with this.
