### ISSUE TITLE
Take a lot of time to run even for a very small data 

### ISSUE THREAD

**Issue by Alalalalaki** [Phlya/adjustText#82]
I change your example to 100 points within a little bit larger figure and then it takes over 1 minute to do the thing. Is there anyway to improve the performance?

 
![image](https://user-images.githubusercontent.com/31154974/59381780-3cbb5980-8d97-11e9-9e1d-4b3e511e1bc3.png)

**Comment by Phlya** [comment]
Hi, yeah, performance is not great! Sorry, it's quite tricky to improve it in general, I think...

But you can try to play with things for a particular example. Simplest thing is of course to reduce the  allowed number of iterations and/or use less strict precision. This might or might not affect the quality of the result significantly.
Playing with forces can help a lot as well, but it's tricky - you need to hit the sweet spot. If the forces are too low, it'll take a long time to fix the overlaps. If they are too large, everything gets very chaotic and might take ages too...

What can also help, if it works for you, is to switch off the self-avoidance of the texts from their original positions and/or other points i.e. `avoid_self=False, avoid_points=False`. But obviously you'll get overlaps between text and data then.

**Comment by Alalalalaki** [comment]
Thanks. This helps. The precision matters a lot.
