### ISSUE TITLE
The text is not aligning properly with the arrows

### ISSUE THREAD

**Issue by Flock1** [Phlya/adjustText#88]
Hi,

I am trying your library but the text is not aligning properly with the arrows. The code I have written is as follows:

```
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)   #top and bottom left
texts = [plt.text(p1_0[i], p2_0[i], idx_0[i]) for i in range(len(p1_0))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='blue'))
ax.scatter(p1_0,p2_0,marker = 'o',label = "Bit flip X")

texts = [plt.text(p1_1[i], p2_1[i], idx_1[i]) for i in range(len(p1_1))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='yellow'))
ax.scatter(p1_1,p2_1,marker = 's', label = "Bit flip Y")

texts = [plt.text(p1_2[i], p2_2[i], idx_2[i]) for i in range(len(p1_2))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='green'))
ax.scatter(p1_2,p2_2,marker = 'd', label = "Hadamard X")

texts = [plt.text(p1_3[i], p2_3[i], idx_3[i]) for i in range(len(p1_3))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='red'))
ax.scatter(p1_3,p2_3,marker = 'x', label = "Hadamard Y")

texts = [plt.text(p1_4[i], p2_4[i], idx_4[i]) for i in range(len(p1_4))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='purple'))
ax.scatter(p1_4,p2_4,marker = '+', label = "measurement")

texts = [plt.text(p1_5[i], p2_5[i], idx_5[i]) for i in range(len(p1_5))]
adjust_text(texts,
            # only_move={'points':'', 'text':'y', 'objects':'y'}, force_text=0.75, force_objects=0.1,
            arrowprops=dict(arrowstyle='->', color='brown'))
ax.scatter(p1_5,p2_5,marker = '^', label = "nothing")
```
I end up getting an image like this
![arrows](https://user-images.githubusercontent.com/15093420/71416217-87daf100-2685-11ea-8bc5-93f21bed5c24.png)

Can you help me?

**Comment by Phlya** [comment]
Hi, can you please make a minimal reproducible example?

**Comment by Flock1** [comment]
What do you mean?

**Comment by Phlya** [comment]
Some code I can copy and run directly that shows the issue.

Sorry, I'm answering from my phone, maybe I'm missing something here.

**Comment by Flock1** [comment]
Oh, okay. That's fine. Answer when you have access to a machine. But please let me know what's the issue. Why is the text not aligning properly?

**Comment by Phlya** [comment]
Some code I could run would help, here you don't include the actual values you used - and it can be much shorter.

**Comment by Flock1** [comment]
Here's are some values. You can assign the parameters these values and you'll get the graph:

https://gist.github.com/Flock1/2af3652a8cea1fb0f8ac69e2501538b0

**Comment by Phlya** [comment]
I can't reproduce your issue. Using your values and your code I get this:
![image](https://user-images.githubusercontent.com/2895034/71441689-2f4e3700-270b-11ea-8625-9ce985bbd4c4.png)

Which versions of adjustText and matplotlib do you have?

Note that in general you should call `adjust_text` once per plot with all the texts, it won't repel objects used in different calls. And to avoid texts with the same coordinates from sticking together, you can add a tiny value to the coordinates, so that they start getting repelled.

**Comment by Flock1** [comment]
Hi

matplotlib: 2.2.3
adjusttext: 0.7.3.1

What do you suggest?

**Comment by Phlya** [comment]
Can you try upgrading matplotlib?

**Comment by Flock1** [comment]
which version?

**Comment by Phlya** [comment]
Something above 3 at least, can you just get the latest?

**Comment by Flock1** [comment]
I'll try that

**Comment by symphorien** [comment]
I had the same problem, and it got better with autoalign=False
