### ISSUE TITLE
plotnine?

### ISSUE THREAD

**Issue by projectsUW** [Phlya/adjustText#90]
How can we use this function in plotnine?

**Comment by Phlya** [comment]
I think it's incorporated into plotnine in `geom_text`.
https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_text.html

I've never used plotnine myself though.

**Comment by Phlya** [comment]
Also, since plotnine is just a wrapper over matplotlib, you can just use adjust_text directly.

I will close for now, feel free to reopen if you have further questions.
