### ISSUE TITLE
Adjust text unexpectedly  slow on scatter plot

### ISSUE THREAD

**Issue by hawkEye-01** [Phlya/adjustText#95]
using for scatter plot with no  more than 30 points. but it takes upto 27 seconds to complete.
Here is a snippet.
am i using it wrong?
i've attached profiler output
[profiler output.txt](https://github.com/Phlya/adjustText/files/4711527/profiler.output.txt)

                    ax = df.plot.scatter(
                        x="x",
                        y="y",
                        s=50 * df.s,
                        color=df.c,
                        alpha=0.6,
                        figsize=(10, 6),
                    )
                    plt.rcParams.update({"font.size": 8})
                    plt.xlabel("P3M Val Share DYA")
                    plt.ylabel("P3M-P12M Val Share")
                    plt.axhline(0, color="lightblue", linewidth=0.5, alpha=0.8)
                    plt.axvline(0, color="lightblue", linewidth=0.5, alpha=0.8)
                    ax.text(
                        0,
                        0,
                        "Collapse",
                        color="red",
                        size="11",
                        horizontalalignment="left",
                        verticalalignment="baseline",
                        transform=ax.transAxes,
                    )
                    ax.text(
                        1,
                        1,
                        "Explode",
                        color="green",
                        size="11",
                        horizontalalignment="right",
                        verticalalignment="top",
                        transform=ax.transAxes,
                    )
                    ax.text(
                        0,
                        1,
                        "Turn",
                        color="orange",
                        size="11",
                        horizontalalignment="left",
                        verticalalignment="top",
                        transform=ax.transAxes,
                    )
                    ax.text(
                        1,
                        0,
                        "Slow",
                        color="gold",
                        size="11",
                        horizontalalignment="right",
                        verticalalignment="baseline",
                        transform=ax.transAxes,
                    )

                    texts = []
                    for i, txt in enumerate(df.label_array):
                        # ax.annotate(txt, (df.x.iat[i],df.y.iat[i]))
                        texts.append(plt.text(df.x.iat[i], df.y.iat[i], txt))
                    adjust_text(texts)
`

**Comment by Phlya** [comment]
Sorry, unfortunately adjust_text is indeed often very slow, and I have some ideas and plans to work on that, but it's not trivial. Without knowing more about your data I can't advice you about how to improve this timing - but there might be ways to tweak the parameters to help it.

**Comment by Hassan-Akhlaq** [comment]
here is a dict of data i am using. see if you can help me with parameters tweak. Thanks

[data.txt](https://github.com/Phlya/adjustText/files/4712009/data.txt)

**Comment by eduamf** [comment]
Today I tried to use adjusttext. It is good, but slow. 
It seems that using ax.scatter is much more slower than using plt.scatter. Setting only_move={'text': 'xy'} is faster. In my case, the point position can't be moved. My code:

```
...
plt.close('all')
plt.style.use('default')
ccluster = minmax_scale(labels, feature_range=(0, 1))
colors = cm.rainbow(ccluster)
txt = []
for t, w in enumerate(wdata):
  plt.scatter(Xc[t,0], Xc[t,1], color=colors[t])
  txt.append(plt.text(Xc[t,0], Xc[t,1], w, size=9))              
plt.title("Direchlet process Gaussian Mixture Model\nPCA dimensionality reduction - %s" % word)
adjust_text(txt, x=Xc[:,0], y=Xc[:,0], only_move={'text': 'xy'}, arrowprops=dict(arrowstyle='-', color='k', lw=0.5))
plt.scatter(Xcw[0,0],Xcw[0,1], c="k", marker="*")
plt.show()
...
```

**Comment by Phlya** [comment]
Can you share a reproducible example, including the data?

**Comment by Phlya** [comment]
It's much faster now!
