### ISSUE TITLE
Add __version__ to `adjustText`

### ISSUE THREAD

**Issue by jolespin** [Phlya/adjustText#96]
There's currently no way to see which version we are using in a compute environment. 

Can you add the following functionality:

```
import adjustText
adjustText.__version__
```

Just like `pandas` and `numpy` do? 

```
import pandas as pd
import numpy as np

print(pd.__version__)
# 1.0.3
print(np.__version__)
# 1.18.4
```

**Comment by Phlya** [comment]
That is a good idea, thank you! Would you like to make a PR for that?

**Comment by jolespin** [comment]
What's the current version on GitHub?

**Comment by Phlya** [comment]
It's in the setup.py file, 0.7.4

**Comment by Phlya** [comment]
Works now
